/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_PDUSessionResourceSetupResponseInfo_MNterminated_H_
#define	_PDUSessionResourceSetupResponseInfo_MNterminated_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DRBsAdmittedList-SetupResponse-MNterminated.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* PDUSessionResourceSetupResponseInfo-MNterminated */
typedef struct PDUSessionResourceSetupResponseInfo_MNterminated {
	DRBsAdmittedList_SetupResponse_MNterminated_t	 dRBsAdmittedList;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDUSessionResourceSetupResponseInfo_MNterminated_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDUSessionResourceSetupResponseInfo_MNterminated;
extern asn_SEQUENCE_specifics_t asn_SPC_PDUSessionResourceSetupResponseInfo_MNterminated_specs_1;
extern asn_TYPE_member_t asn_MBR_PDUSessionResourceSetupResponseInfo_MNterminated_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PDUSessionResourceSetupResponseInfo_MNterminated_H_ */
#include <asn_internal.h>
