/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_ReservedSubframePattern_H_
#define	_ReservedSubframePattern_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <BIT_STRING.h>
#include "MBSFNControlRegionLength.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReservedSubframePattern__subframeType {
	ReservedSubframePattern__subframeType_mbsfn	= 0,
	ReservedSubframePattern__subframeType_non_mbsfn	= 1
	/*
	 * Enumeration is extensible
	 */
} e_ReservedSubframePattern__subframeType;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* ReservedSubframePattern */
typedef struct ReservedSubframePattern {
	long	 subframeType;
	BIT_STRING_t	 reservedSubframePattern;
	MBSFNControlRegionLength_t	*mbsfnControlRegionLength	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReservedSubframePattern_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_subframeType_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ReservedSubframePattern;
extern asn_SEQUENCE_specifics_t asn_SPC_ReservedSubframePattern_specs_1;
extern asn_TYPE_member_t asn_MBR_ReservedSubframePattern_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _ReservedSubframePattern_H_ */
#include <asn_internal.h>
