/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-Containers"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#include "ASN_XNAP_ProtocolIE-Single-Container.h"

/*
 * This type is implemented using ProtocolIE_Field_5957P0,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Single_Container_5954P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Single_Container_5954P0 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_Single_Container_5954P0_tags_1,
	sizeof(asn_DEF_ProtocolIE_Single_Container_5954P0_tags_1)
		/sizeof(asn_DEF_ProtocolIE_Single_Container_5954P0_tags_1[0]), /* 1 */
	asn_DEF_ProtocolIE_Single_Container_5954P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Single_Container_5954P0_tags_1)
		/sizeof(asn_DEF_ProtocolIE_Single_Container_5954P0_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ProtocolIE_Field_5957P0_1,
	3,	/* Elements count */
	&asn_SPC_ProtocolIE_Field_5957P0_specs_1	/* Additional specs */
};

