/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_SpecialSubframePatterns_E_UTRA_H_
#define	_SpecialSubframePatterns_E_UTRA_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_XNAP_SpecialSubframePatterns_E_UTRA {
    ASN_XNAP_SpecialSubframePatterns_E_UTRA_ssp0	= 0,
    ASN_XNAP_SpecialSubframePatterns_E_UTRA_ssp1	= 1,
    ASN_XNAP_SpecialSubframePatterns_E_UTRA_ssp2	= 2,
    ASN_XNAP_SpecialSubframePatterns_E_UTRA_ssp3	= 3,
    ASN_XNAP_SpecialSubframePatterns_E_UTRA_ssp4	= 4,
    ASN_XNAP_SpecialSubframePatterns_E_UTRA_ssp5	= 5,
    ASN_XNAP_SpecialSubframePatterns_E_UTRA_ssp6	= 6,
    ASN_XNAP_SpecialSubframePatterns_E_UTRA_ssp7	= 7,
    ASN_XNAP_SpecialSubframePatterns_E_UTRA_ssp8	= 8,
    ASN_XNAP_SpecialSubframePatterns_E_UTRA_ssp9	= 9,
    ASN_XNAP_SpecialSubframePatterns_E_UTRA_ssp10	= 10
	/*
	 * Enumeration is extensible
	 */
} e_ASN_XNAP_SpecialSubframePatterns_E_UTRA;

/* SpecialSubframePatterns-E-UTRA */
typedef long	 ASN_XNAP_SpecialSubframePatterns_E_UTRA_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ASN_XNAP_SpecialSubframePatterns_E_UTRA_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ASN_XNAP_SpecialSubframePatterns_E_UTRA;
extern const asn_INTEGER_specifics_t asn_SPC_ASN_XNAP_SpecialSubframePatterns_E_UTRA_specs_1;
asn_struct_free_f SpecialSubframePatterns_E_UTRA_free;
asn_struct_print_f SpecialSubframePatterns_E_UTRA_print;
asn_constr_check_f SpecialSubframePatterns_E_UTRA_constraint;
ber_type_decoder_f SpecialSubframePatterns_E_UTRA_decode_ber;
der_type_encoder_f SpecialSubframePatterns_E_UTRA_encode_der;
xer_type_decoder_f SpecialSubframePatterns_E_UTRA_decode_xer;
xer_type_encoder_f SpecialSubframePatterns_E_UTRA_encode_xer;
per_type_decoder_f SpecialSubframePatterns_E_UTRA_decode_uper;
per_type_encoder_f SpecialSubframePatterns_E_UTRA_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SpecialSubframePatterns_E_UTRA_H_ */
#include <asn_internal.h>
