/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-PDU-Contents"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_UEContextInfo_SNModRequest_H_
#define	_UEContextInfo_SNModRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "S-NG-RANnode-SecurityKey.h"
#include "RFSP-Index.h"
#include "LowerLayerPresenceStatusChange.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UESecurityCapabilities;
struct UEAggregateMaximumBitRate;
struct PDUSessionsToBeAdded_SNModRequest_List;
struct PDUSessionsToBeModified_SNModRequest_List;
struct PDUSessionsToBeReleased_SNModRequest_List;
struct ProtocolExtensionContainer;

/* UEContextInfo-SNModRequest */
typedef struct UEContextInfo_SNModRequest {
	struct UESecurityCapabilities	*ueSecurityCapabilities	/* OPTIONAL */;
	S_NG_RANnode_SecurityKey_t	*s_ng_RANnode_SecurityKey	/* OPTIONAL */;
	struct UEAggregateMaximumBitRate	*s_ng_RANnodeUE_AMBR	/* OPTIONAL */;
	RFSP_Index_t	*indexToRatFrequencySelectionPriority	/* OPTIONAL */;
	LowerLayerPresenceStatusChange_t	*lowerLayerPresenceStatusChange	/* OPTIONAL */;
	struct PDUSessionsToBeAdded_SNModRequest_List	*pduSessionResourceToBeAdded	/* OPTIONAL */;
	struct PDUSessionsToBeModified_SNModRequest_List	*pduSessionResourceToBeModified	/* OPTIONAL */;
	struct PDUSessionsToBeReleased_SNModRequest_List	*pduSessionResourceToBeReleased	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEContextInfo_SNModRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEContextInfo_SNModRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _UEContextInfo_SNModRequest_H_ */
#include <asn_internal.h>
