/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_DRBsToBeModified_List_ModRqd_MNterminated_H_
#define	_DRBsToBeModified_List_ModRqd_MNterminated_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DRBsToBeModified_List_ModRqd_MNterminated_Item;

/* DRBsToBeModified-List-ModRqd-MNterminated */
typedef struct DRBsToBeModified_List_ModRqd_MNterminated {
	A_SEQUENCE_OF(struct DRBsToBeModified_List_ModRqd_MNterminated_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DRBsToBeModified_List_ModRqd_MNterminated_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DRBsToBeModified_List_ModRqd_MNterminated;
extern asn_SET_OF_specifics_t asn_SPC_DRBsToBeModified_List_ModRqd_MNterminated_specs_1;
extern asn_TYPE_member_t asn_MBR_DRBsToBeModified_List_ModRqd_MNterminated_1[1];
extern asn_per_constraints_t asn_PER_type_DRBsToBeModified_List_ModRqd_MNterminated_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _DRBsToBeModified_List_ModRqd_MNterminated_H_ */
#include <asn_internal.h>
