/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_Additional_UL_NG_U_TNLatUPF_List_H_
#define	_Additional_UL_NG_U_TNLatUPF_List_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Additional_UL_NG_U_TNLatUPF_Item;

/* Additional-UL-NG-U-TNLatUPF-List */
typedef struct Additional_UL_NG_U_TNLatUPF_List {
	A_SEQUENCE_OF(struct Additional_UL_NG_U_TNLatUPF_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Additional_UL_NG_U_TNLatUPF_List_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Additional_UL_NG_U_TNLatUPF_List;

#ifdef __cplusplus
}
#endif

#endif	/* _Additional_UL_NG_U_TNLatUPF_List_H_ */
#include <asn_internal.h>
