/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_PDUSessionResourceSecondaryRATUsageItem_H_
#define	_PDUSessionResourceSecondaryRATUsageItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PDUSession-ID.h"
#include "SecondaryRATUsageInformation.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* PDUSessionResourceSecondaryRATUsageItem */
typedef struct PDUSessionResourceSecondaryRATUsageItem {
	PDUSession_ID_t	 pDUSessionID;
	SecondaryRATUsageInformation_t	 secondaryRATUsageInformation;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDUSessionResourceSecondaryRATUsageItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDUSessionResourceSecondaryRATUsageItem;
extern asn_SEQUENCE_specifics_t asn_SPC_PDUSessionResourceSecondaryRATUsageItem_specs_1;
extern asn_TYPE_member_t asn_MBR_PDUSessionResourceSecondaryRATUsageItem_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _PDUSessionResourceSecondaryRATUsageItem_H_ */
#include <asn_internal.h>
