/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_GUAMI_H_
#define	_GUAMI_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMN-Identity.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* GUAMI */
typedef struct GUAMI {
	PLMN_Identity_t	 plmn_ID;
	BIT_STRING_t	 amf_region_id;
	BIT_STRING_t	 amf_set_id;
	BIT_STRING_t	 amf_pointer;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GUAMI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GUAMI;

#ifdef __cplusplus
}
#endif

#endif	/* _GUAMI_H_ */
#include <asn_internal.h>
