/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_NeighbourInformation_NR_ModeFDDInfo_H_
#define	_NeighbourInformation_NR_ModeFDDInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRFrequencyInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* NeighbourInformation-NR-ModeFDDInfo */
typedef struct NeighbourInformation_NR_ModeFDDInfo {
	NRFrequencyInfo_t	 ul_NR_FreqInfo;
	NRFrequencyInfo_t	 dl_NR_FequInfo;
	struct ProtocolExtensionContainer	*ie_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NeighbourInformation_NR_ModeFDDInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NeighbourInformation_NR_ModeFDDInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_NeighbourInformation_NR_ModeFDDInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_NeighbourInformation_NR_ModeFDDInfo_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _NeighbourInformation_NR_ModeFDDInfo_H_ */
#include <asn_internal.h>
