/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_PDUSession_ID_H_
#define	_PDUSession_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PDUSession-ID */
typedef long	 PDUSession_ID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PDUSession_ID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PDUSession_ID;
asn_struct_free_f PDUSession_ID_free;
asn_struct_print_f PDUSession_ID_print;
asn_constr_check_f PDUSession_ID_constraint;
ber_type_decoder_f PDUSession_ID_decode_ber;
der_type_encoder_f PDUSession_ID_encode_der;
xer_type_decoder_f PDUSession_ID_decode_xer;
xer_type_encoder_f PDUSession_ID_encode_xer;
per_type_decoder_f PDUSession_ID_decode_uper;
per_type_encoder_f PDUSession_ID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PDUSession_ID_H_ */
#include <asn_internal.h>
