/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#include "PDUSessionResourceModConfirmInfo-SNterminated.h"

#include "UPTransportLayerInformation.h"
#include "DRB-List-withCause.h"
#include "DataForwardingInfoFromTargetNGRANnode.h"
#include "ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_PDUSessionResourceModConfirmInfo_SNterminated_1[] = {
	{ ATF_POINTER, 1, offsetof(struct PDUSessionResourceModConfirmInfo_SNterminated, uL_NG_U_TNLatUPF),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UPTransportLayerInformation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uL-NG-U-TNLatUPF"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDUSessionResourceModConfirmInfo_SNterminated, dRBsAdmittedList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRBsAdmittedList_ModConfirm_SNterminated,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dRBsAdmittedList"
		},
	{ ATF_POINTER, 3, offsetof(struct PDUSessionResourceModConfirmInfo_SNterminated, dRBsNotAdmittedSetupModifyList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRB_List_withCause,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dRBsNotAdmittedSetupModifyList"
		},
	{ ATF_POINTER, 2, offsetof(struct PDUSessionResourceModConfirmInfo_SNterminated, dataforwardinginfoTarget),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataForwardingInfoFromTargetNGRANnode,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dataforwardinginfoTarget"
		},
	{ ATF_POINTER, 1, offsetof(struct PDUSessionResourceModConfirmInfo_SNterminated, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_6001P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_PDUSessionResourceModConfirmInfo_SNterminated_oms_1[] = { 0, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_PDUSessionResourceModConfirmInfo_SNterminated_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PDUSessionResourceModConfirmInfo_SNterminated_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* uL-NG-U-TNLatUPF */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dRBsAdmittedList */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* dRBsNotAdmittedSetupModifyList */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* dataforwardinginfoTarget */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_PDUSessionResourceModConfirmInfo_SNterminated_specs_1 = {
	sizeof(struct PDUSessionResourceModConfirmInfo_SNterminated),
	offsetof(struct PDUSessionResourceModConfirmInfo_SNterminated, _asn_ctx),
	asn_MAP_PDUSessionResourceModConfirmInfo_SNterminated_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_PDUSessionResourceModConfirmInfo_SNterminated_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PDUSessionResourceModConfirmInfo_SNterminated = {
	"PDUSessionResourceModConfirmInfo-SNterminated",
	"PDUSessionResourceModConfirmInfo-SNterminated",
	&asn_OP_SEQUENCE,
	asn_DEF_PDUSessionResourceModConfirmInfo_SNterminated_tags_1,
	sizeof(asn_DEF_PDUSessionResourceModConfirmInfo_SNterminated_tags_1)
		/sizeof(asn_DEF_PDUSessionResourceModConfirmInfo_SNterminated_tags_1[0]), /* 1 */
	asn_DEF_PDUSessionResourceModConfirmInfo_SNterminated_tags_1,	/* Same as above */
	sizeof(asn_DEF_PDUSessionResourceModConfirmInfo_SNterminated_tags_1)
		/sizeof(asn_DEF_PDUSessionResourceModConfirmInfo_SNterminated_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PDUSessionResourceModConfirmInfo_SNterminated_1,
	5,	/* Elements count */
	&asn_SPC_PDUSessionResourceModConfirmInfo_SNterminated_specs_1	/* Additional specs */
};

