/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#include "CauseRadioNetworkLayer.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
asn_per_constraints_t asn_PER_type_CauseRadioNetworkLayer_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  6,  6,  0,  52 }	/* (0..52,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_CauseRadioNetworkLayer_value2enum_1[] = {
	{ 0,	18,	"cell-not-available" },
	{ 1,	36,	"handover-desirable-for-radio-reasons" },
	{ 2,	27,	"handover-target-not-allowed" },
	{ 3,	18,	"invalid-AMF-Set-ID" },
	{ 4,	43,	"no-radio-resources-available-in-target-cell" },
	{ 5,	16,	"partial-handover" },
	{ 6,	27,	"reduce-load-in-serving-cell" },
	{ 7,	30,	"resource-optimisation-handover" },
	{ 8,	22,	"time-critical-handover" },
	{ 9,	22,	"tXnRELOCoverall-expiry" },
	{ 10,	20,	"tTXnRELOCprep-expiry" },
	{ 11,	16,	"unknown-GUAMI-ID" },
	{ 12,	36,	"unknown-local-NG-RAN-node-UE-XnAP-ID" },
	{ 13,	42,	"inconsistent-remote-NG-RAN-node-UE-XnAP-ID" },
	{ 14,	63,	"encryption-and-or-integrity-protection-algorithms-not-supported" },
	{ 15,	35,	"protection-algorithms-not-supported" },
	{ 16,	33,	"multiple-PDU-session-ID-instances" },
	{ 17,	22,	"unknown-PDU-session-ID" },
	{ 18,	19,	"unknown-QoS-Flow-ID" },
	{ 19,	30,	"multiple-QoS-Flow-ID-instances" },
	{ 20,	18,	"switch-off-ongoing" },
	{ 21,	23,	"not-supported-5QI-value" },
	{ 22,	19,	"tXnDCoverall-expiry" },
	{ 23,	16,	"tXnDCprep-expiry" },
	{ 24,	34,	"action-desirable-for-radio-reasons" },
	{ 25,	11,	"reduce-load" },
	{ 26,	21,	"resource-optimisation" },
	{ 27,	20,	"time-critical-action" },
	{ 28,	18,	"target-not-allowed" },
	{ 29,	28,	"no-radio-resources-available" },
	{ 30,	23,	"invalid-QoS-combination" },
	{ 31,	35,	"encryption-algorithms-not-supported" },
	{ 32,	19,	"procedure-cancelled" },
	{ 33,	11,	"rRM-purpose" },
	{ 34,	21,	"improve-user-bit-rate" },
	{ 35,	15,	"user-inactivity" },
	{ 36,	29,	"radio-connection-with-UE-lost" },
	{ 37,	40,	"failure-in-the-radio-interface-procedure" },
	{ 38,	27,	"bearer-option-not-supported" },
	{ 39,	36,	"up-integrity-protection-not-possible" },
	{ 40,	42,	"up-confidentiality-protection-not-possible" },
	{ 41,	39,	"resources-not-available-for-the-slice-s" },
	{ 42,	26,	"ue-max-IP-data-rate-reason" },
	{ 43,	31,	"cP-integrity-protection-failure" },
	{ 44,	31,	"uP-integrity-protection-failure" },
	{ 45,	29,	"slice-not-supported-by-NG-RAN" },
	{ 46,	11,	"mN-Mobility" },
	{ 47,	11,	"sN-Mobility" },
	{ 48,	23,	"count-reaches-max-value" },
	{ 49,	29,	"unknown-old-en-gNB-UE-X2AP-ID" },
	{ 50,	13,	"pDCP-Overload" },
	{ 51,	20,	"drb-id-not-available" },
	{ 52,	11,	"unspecified" },
	{ 53,	23,	"ue-context-id-not-known" },
	{ 54,	25,	"non-relocation-of-context" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_CauseRadioNetworkLayer_enum2value_1[] = {
	24,	/* action-desirable-for-radio-reasons(24) */
	38,	/* bearer-option-not-supported(38) */
	43,	/* cP-integrity-protection-failure(43) */
	0,	/* cell-not-available(0) */
	48,	/* count-reaches-max-value(48) */
	51,	/* drb-id-not-available(51) */
	31,	/* encryption-algorithms-not-supported(31) */
	14,	/* encryption-and-or-integrity-protection-algorithms-not-supported(14) */
	37,	/* failure-in-the-radio-interface-procedure(37) */
	1,	/* handover-desirable-for-radio-reasons(1) */
	2,	/* handover-target-not-allowed(2) */
	34,	/* improve-user-bit-rate(34) */
	13,	/* inconsistent-remote-NG-RAN-node-UE-XnAP-ID(13) */
	3,	/* invalid-AMF-Set-ID(3) */
	30,	/* invalid-QoS-combination(30) */
	46,	/* mN-Mobility(46) */
	16,	/* multiple-PDU-session-ID-instances(16) */
	19,	/* multiple-QoS-Flow-ID-instances(19) */
	29,	/* no-radio-resources-available(29) */
	4,	/* no-radio-resources-available-in-target-cell(4) */
	54,	/* non-relocation-of-context(54) */
	21,	/* not-supported-5QI-value(21) */
	50,	/* pDCP-Overload(50) */
	5,	/* partial-handover(5) */
	32,	/* procedure-cancelled(32) */
	15,	/* protection-algorithms-not-supported(15) */
	33,	/* rRM-purpose(33) */
	36,	/* radio-connection-with-UE-lost(36) */
	25,	/* reduce-load(25) */
	6,	/* reduce-load-in-serving-cell(6) */
	26,	/* resource-optimisation(26) */
	7,	/* resource-optimisation-handover(7) */
	41,	/* resources-not-available-for-the-slice-s(41) */
	47,	/* sN-Mobility(47) */
	45,	/* slice-not-supported-by-NG-RAN(45) */
	20,	/* switch-off-ongoing(20) */
	10,	/* tTXnRELOCprep-expiry(10) */
	22,	/* tXnDCoverall-expiry(22) */
	23,	/* tXnDCprep-expiry(23) */
	9,	/* tXnRELOCoverall-expiry(9) */
	28,	/* target-not-allowed(28) */
	27,	/* time-critical-action(27) */
	8,	/* time-critical-handover(8) */
	44,	/* uP-integrity-protection-failure(44) */
	53,	/* ue-context-id-not-known(53) */
	42,	/* ue-max-IP-data-rate-reason(42) */
	11,	/* unknown-GUAMI-ID(11) */
	17,	/* unknown-PDU-session-ID(17) */
	18,	/* unknown-QoS-Flow-ID(18) */
	12,	/* unknown-local-NG-RAN-node-UE-XnAP-ID(12) */
	49,	/* unknown-old-en-gNB-UE-X2AP-ID(49) */
	52,	/* unspecified(52) */
	40,	/* up-confidentiality-protection-not-possible(40) */
	39,	/* up-integrity-protection-not-possible(39) */
	35	/* user-inactivity(35) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_CauseRadioNetworkLayer_specs_1 = {
	asn_MAP_CauseRadioNetworkLayer_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_CauseRadioNetworkLayer_enum2value_1,	/* N => "tag"; sorted by N */
	55,	/* Number of elements in the maps */
	54,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_CauseRadioNetworkLayer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_CauseRadioNetworkLayer = {
	"CauseRadioNetworkLayer",
	"CauseRadioNetworkLayer",
	&asn_OP_NativeEnumerated,
	asn_DEF_CauseRadioNetworkLayer_tags_1,
	sizeof(asn_DEF_CauseRadioNetworkLayer_tags_1)
		/sizeof(asn_DEF_CauseRadioNetworkLayer_tags_1[0]), /* 1 */
	asn_DEF_CauseRadioNetworkLayer_tags_1,	/* Same as above */
	sizeof(asn_DEF_CauseRadioNetworkLayer_tags_1)
		/sizeof(asn_DEF_CauseRadioNetworkLayer_tags_1[0]), /* 1 */
	{ 0, &asn_PER_type_CauseRadioNetworkLayer_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_CauseRadioNetworkLayer_specs_1	/* Additional specs */
};

