/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_PDUSessionResourceSetupResponseInfo_SNterminated_H_
#define	_PDUSessionResourceSetupResponseInfo_SNterminated_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_XNAP_UPTransportLayerInformation.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASN_XNAP_DRBsToBeSetupList_SetupResponse_SNterminated;
struct ASN_XNAP_DataForwardingInfoFromTargetNGRANnode;
struct ASN_XNAP_QoSFlows_List_withCause;
struct ASN_XNAP_SecurityResult;
struct ASN_XNAP_ProtocolExtensionContainer;

/* PDUSessionResourceSetupResponseInfo-SNterminated */
typedef struct ASN_XNAP_PDUSessionResourceSetupResponseInfo_SNterminated {
    ASN_XNAP_UPTransportLayerInformation_t	 dL_NG_U_TNLatNG_RAN;
	struct ASN_XNAP_DRBsToBeSetupList_SetupResponse_SNterminated	*dRBsToBeSetup	/* OPTIONAL */;
	struct ASN_XNAP_DataForwardingInfoFromTargetNGRANnode	*dataforwardinginfoTarget	/* OPTIONAL */;
	struct ASN_XNAP_QoSFlows_List_withCause	*qosFlowsNotAdmittedList	/* OPTIONAL */;
	struct ASN_XNAP_SecurityResult	*securityResult	/* OPTIONAL */;
	struct ASN_XNAP_ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_PDUSessionResourceSetupResponseInfo_SNterminated_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDUSessionResourceSetupResponseInfo_SNterminated;
extern asn_SEQUENCE_specifics_t asn_SPC_PDUSessionResourceSetupResponseInfo_SNterminated_specs_1;
extern asn_TYPE_member_t asn_MBR_PDUSessionResourceSetupResponseInfo_SNterminated_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _PDUSessionResourceSetupResponseInfo_SNterminated_H_ */
#include <asn_internal.h>
