/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_UEContextInfoRetrUECtxtResp_H_
#define	_UEContextInfoRetrUECtxtResp_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AMF-UE-NGAP-ID.h"
#include "CPTransportLayerInformation.h"
#include "UESecurityCapabilities.h"
#include "AS-SecurityInformation.h"
#include "UEAggregateMaximumBitRate.h"
#include "PDUSessionResourcesToBeSetup-List.h"
#include <OCTET_STRING.h>
#include "RFSP-Index.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MobilityRestrictionList;
struct ProtocolExtensionContainer;

/* UEContextInfoRetrUECtxtResp */
typedef struct UEContextInfoRetrUECtxtResp {
	AMF_UE_NGAP_ID_t	 ng_c_UE_signalling_ref;
	CPTransportLayerInformation_t	 signalling_TNL_at_source;
	UESecurityCapabilities_t	 ueSecurityCapabilities;
	AS_SecurityInformation_t	 securityInformation;
	UEAggregateMaximumBitRate_t	 ue_AMBR;
	PDUSessionResourcesToBeSetup_List_t	 pduSessionResourcesToBeSetup_List;
	OCTET_STRING_t	 rrc_Context;
	struct MobilityRestrictionList	*mobilityRestrictionList	/* OPTIONAL */;
	RFSP_Index_t	*indexToRatFrequencySelectionPriority	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEContextInfoRetrUECtxtResp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEContextInfoRetrUECtxtResp;

#ifdef __cplusplus
}
#endif

#endif	/* _UEContextInfoRetrUECtxtResp_H_ */
#include <asn_internal.h>
