/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_DesiredActNotificationLevel_H_
#define	_DesiredActNotificationLevel_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DesiredActNotificationLevel {
	DesiredActNotificationLevel_none	= 0,
	DesiredActNotificationLevel_qos_flow	= 1,
	DesiredActNotificationLevel_pdu_session	= 2,
	DesiredActNotificationLevel_ue_level	= 3
	/*
	 * Enumeration is extensible
	 */
} e_DesiredActNotificationLevel;

/* DesiredActNotificationLevel */
typedef long	 DesiredActNotificationLevel_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DesiredActNotificationLevel;
asn_struct_free_f DesiredActNotificationLevel_free;
asn_struct_print_f DesiredActNotificationLevel_print;
asn_constr_check_f DesiredActNotificationLevel_constraint;
ber_type_decoder_f DesiredActNotificationLevel_decode_ber;
der_type_encoder_f DesiredActNotificationLevel_encode_der;
xer_type_decoder_f DesiredActNotificationLevel_decode_xer;
xer_type_encoder_f DesiredActNotificationLevel_encode_xer;
per_type_decoder_f DesiredActNotificationLevel_decode_uper;
per_type_encoder_f DesiredActNotificationLevel_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DesiredActNotificationLevel_H_ */
#include <asn_internal.h>
