/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-PDU-Contents"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_PDUSessionsToBeReleased_SNModRequest_List_H_
#define	_PDUSessionsToBeReleased_SNModRequest_List_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASN_XNAP_PDUSession_List_withCause;
struct ASN_XNAP_ProtocolExtensionContainer;

/* PDUSessionsToBeReleased-SNModRequest-List */
typedef struct ASN_XNAP_PDUSessionsToBeReleased_SNModRequest_List {
	struct ASN_XNAP_PDUSession_List_withCause	*pdu_session_list	/* OPTIONAL */;
	struct ASN_XNAP_ProtocolExtensionContainer	*iE_Extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_PDUSessionsToBeReleased_SNModRequest_List_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDUSessionsToBeReleased_SNModRequest_List;
extern asn_SEQUENCE_specifics_t asn_SPC_PDUSessionsToBeReleased_SNModRequest_List_specs_1;
extern asn_TYPE_member_t asn_MBR_PDUSessionsToBeReleased_SNModRequest_List_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PDUSessionsToBeReleased_SNModRequest_List_H_ */
#include <asn_internal.h>
