/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_S_NG_RANnode_SecurityKey_H_
#define	_S_NG_RANnode_SecurityKey_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* S-NG-RANnode-SecurityKey */
typedef BIT_STRING_t	 ASN_XNAP_S_NG_RANnode_SecurityKey_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_S_NG_RANnode_SecurityKey_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_S_NG_RANnode_SecurityKey;
asn_struct_free_f S_NG_RANnode_SecurityKey_free;
asn_struct_print_f S_NG_RANnode_SecurityKey_print;
asn_constr_check_f S_NG_RANnode_SecurityKey_constraint;
ber_type_decoder_f S_NG_RANnode_SecurityKey_decode_ber;
der_type_encoder_f S_NG_RANnode_SecurityKey_encode_der;
xer_type_decoder_f S_NG_RANnode_SecurityKey_decode_xer;
xer_type_encoder_f S_NG_RANnode_SecurityKey_encode_xer;
per_type_decoder_f S_NG_RANnode_SecurityKey_decode_uper;
per_type_encoder_f S_NG_RANnode_SecurityKey_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _S_NG_RANnode_SecurityKey_H_ */
#include <asn_internal.h>
