/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_PDUSessionResourceBearerSetupCompleteInfo_SNterminated_H_
#define	_PDUSessionResourceBearerSetupCompleteInfo_SNterminated_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;
struct DRBsToBeSetupList_BearerSetupComplete_SNterminated_Item;

/* PDUSessionResourceBearerSetupCompleteInfo-SNterminated */
typedef struct PDUSessionResourceBearerSetupCompleteInfo_SNterminated {
	struct PDUSessionResourceBearerSetupCompleteInfo_SNterminated__dRBsToBeSetupList {
		A_SEQUENCE_OF(struct DRBsToBeSetupList_BearerSetupComplete_SNterminated_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} dRBsToBeSetupList;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDUSessionResourceBearerSetupCompleteInfo_SNterminated_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDUSessionResourceBearerSetupCompleteInfo_SNterminated;
extern asn_SEQUENCE_specifics_t asn_SPC_PDUSessionResourceBearerSetupCompleteInfo_SNterminated_specs_1;
extern asn_TYPE_member_t asn_MBR_PDUSessionResourceBearerSetupCompleteInfo_SNterminated_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PDUSessionResourceBearerSetupCompleteInfo_SNterminated_H_ */
#include <asn_internal.h>
