/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-PDU-Contents"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#include "ResourceCoordRequest-gNB-initiated.h"

#include "ProtocolExtensionContainer.h"
#include "E-UTRA-CGI.h"
#include "NR-CGI.h"
static int
memb_listofE_UTRACells_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 16384)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_listofNRCells_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 16384)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_listofE_UTRACells_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 14,  14,  1,  16384 }	/* (SIZE(1..16384)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_listofNRCells_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 14,  14,  1,  16384 }	/* (SIZE(1..16384)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_listofE_UTRACells_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 14,  14,  1,  16384 }	/* (SIZE(1..16384)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_listofNRCells_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 14,  14,  1,  16384 }	/* (SIZE(1..16384)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_listofE_UTRACells_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E_UTRA_CGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_listofE_UTRACells_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listofE_UTRACells_specs_3 = {
	sizeof(struct ResourceCoordRequest_gNB_initiated__listofE_UTRACells),
	offsetof(struct ResourceCoordRequest_gNB_initiated__listofE_UTRACells, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listofE_UTRACells_3 = {
	"listofE-UTRACells",
	"listofE-UTRACells",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_listofE_UTRACells_tags_3,
	sizeof(asn_DEF_listofE_UTRACells_tags_3)
		/sizeof(asn_DEF_listofE_UTRACells_tags_3[0]) - 1, /* 1 */
	asn_DEF_listofE_UTRACells_tags_3,	/* Same as above */
	sizeof(asn_DEF_listofE_UTRACells_tags_3)
		/sizeof(asn_DEF_listofE_UTRACells_tags_3[0]), /* 2 */
	{ 0, &asn_PER_type_listofE_UTRACells_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_listofE_UTRACells_3,
	1,	/* Single element */
	&asn_SPC_listofE_UTRACells_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_listofNRCells_6[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NR_CGI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_listofNRCells_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listofNRCells_specs_6 = {
	sizeof(struct ResourceCoordRequest_gNB_initiated__listofNRCells),
	offsetof(struct ResourceCoordRequest_gNB_initiated__listofNRCells, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listofNRCells_6 = {
	"listofNRCells",
	"listofNRCells",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_listofNRCells_tags_6,
	sizeof(asn_DEF_listofNRCells_tags_6)
		/sizeof(asn_DEF_listofNRCells_tags_6[0]) - 1, /* 1 */
	asn_DEF_listofNRCells_tags_6,	/* Same as above */
	sizeof(asn_DEF_listofNRCells_tags_6)
		/sizeof(asn_DEF_listofNRCells_tags_6[0]), /* 2 */
	{ 0, &asn_PER_type_listofNRCells_constr_6, SEQUENCE_OF_constraint },
	asn_MBR_listofNRCells_6,
	1,	/* Single element */
	&asn_SPC_listofNRCells_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ResourceCoordRequest_gNB_initiated_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ResourceCoordRequest_gNB_initiated, dataTrafficResourceIndication),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataTrafficResourceIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dataTrafficResourceIndication"
		},
	{ ATF_POINTER, 1, offsetof(struct ResourceCoordRequest_gNB_initiated, listofE_UTRACells),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_listofE_UTRACells_3,
		0,
		{ 0, &asn_PER_memb_listofE_UTRACells_constr_3,  memb_listofE_UTRACells_constraint_1 },
		0, 0, /* No default value */
		"listofE-UTRACells"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ResourceCoordRequest_gNB_initiated, spectrumSharingGroupID),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SpectrumSharingGroupID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"spectrumSharingGroupID"
		},
	{ ATF_POINTER, 2, offsetof(struct ResourceCoordRequest_gNB_initiated, listofNRCells),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_listofNRCells_6,
		0,
		{ 0, &asn_PER_memb_listofNRCells_constr_6,  memb_listofNRCells_constraint_1 },
		0, 0, /* No default value */
		"listofNRCells"
		},
	{ ATF_POINTER, 1, offsetof(struct ResourceCoordRequest_gNB_initiated, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_6001P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_ResourceCoordRequest_gNB_initiated_oms_1[] = { 1, 3, 4 };
static const ber_tlv_tag_t asn_DEF_ResourceCoordRequest_gNB_initiated_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ResourceCoordRequest_gNB_initiated_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dataTrafficResourceIndication */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* listofE-UTRACells */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* spectrumSharingGroupID */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* listofNRCells */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_ResourceCoordRequest_gNB_initiated_specs_1 = {
	sizeof(struct ResourceCoordRequest_gNB_initiated),
	offsetof(struct ResourceCoordRequest_gNB_initiated, _asn_ctx),
	asn_MAP_ResourceCoordRequest_gNB_initiated_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_ResourceCoordRequest_gNB_initiated_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ResourceCoordRequest_gNB_initiated = {
	"ResourceCoordRequest-gNB-initiated",
	"ResourceCoordRequest-gNB-initiated",
	&asn_OP_SEQUENCE,
	asn_DEF_ResourceCoordRequest_gNB_initiated_tags_1,
	sizeof(asn_DEF_ResourceCoordRequest_gNB_initiated_tags_1)
		/sizeof(asn_DEF_ResourceCoordRequest_gNB_initiated_tags_1[0]), /* 1 */
	asn_DEF_ResourceCoordRequest_gNB_initiated_tags_1,	/* Same as above */
	sizeof(asn_DEF_ResourceCoordRequest_gNB_initiated_tags_1)
		/sizeof(asn_DEF_ResourceCoordRequest_gNB_initiated_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ResourceCoordRequest_gNB_initiated_1,
	5,	/* Elements count */
	&asn_SPC_ResourceCoordRequest_gNB_initiated_specs_1	/* Additional specs */
};

