/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-PDU-Contents"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_PDUSessionReleasedSNModConfirm_H_
#define	_PDUSessionReleasedSNModConfirm_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PDUSession_List_withDataForwardingFromTarget;
struct PDUSession_List;
struct ProtocolExtensionContainer;

/* PDUSessionReleasedSNModConfirm */
typedef struct PDUSessionReleasedSNModConfirm {
	struct PDUSession_List_withDataForwardingFromTarget	*sn_terminated	/* OPTIONAL */;
	struct PDUSession_List	*mn_terminated	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDUSessionReleasedSNModConfirm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDUSessionReleasedSNModConfirm;

#ifdef __cplusplus
}
#endif

#endif	/* _PDUSessionReleasedSNModConfirm_H_ */
#include <asn_internal.h>
