/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_TNLA_To_Update_Item_H_
#define	_TNLA_To_Update_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_XNAP_CPTransportLayerInformation.h"
#include "ASN_XNAP_TNLAssociationUsage.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASN_XNAP_ProtocolExtensionContainer;

/* TNLA-To-Update-Item */
typedef struct ASN_XNAP_TNLA_To_Update_Item {
    ASN_XNAP_CPTransportLayerInformation_t	 tNLAssociationTransportLayerAddress;
    ASN_XNAP_TNLAssociationUsage_t	*tNLAssociationUsage	/* OPTIONAL */;
	struct ASN_XNAP_ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_TNLA_To_Update_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TNLA_To_Update_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_TNLA_To_Update_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_TNLA_To_Update_Item_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _TNLA_To_Update_Item_H_ */
#include <asn_internal.h>
