/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-PDU-Contents"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#include "ResponseType-ReconfComplete.h"

#include "Configuration-successfully-applied.h"
#include "Configuration-rejected-by-M-NG-RANNode.h"
#include "ProtocolIE-Single-Container.h"
asn_per_constraints_t asn_PER_type_ResponseType_ReconfComplete_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ResponseType_ReconfComplete_1[] = {
	{ ATF_POINTER, 0, offsetof(struct ResponseType_ReconfComplete, choice.configuration_successfully_applied),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Configuration_successfully_applied,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"configuration-successfully-applied"
		},
	{ ATF_POINTER, 0, offsetof(struct ResponseType_ReconfComplete, choice.configuration_rejected_by_M_NG_RANNode),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Configuration_rejected_by_M_NG_RANNode,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"configuration-rejected-by-M-NG-RANNode"
		},
	{ ATF_POINTER, 0, offsetof(struct ResponseType_ReconfComplete, choice.choice_extension),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolIE_Single_Container_5954P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"choice-extension"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ResponseType_ReconfComplete_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* configuration-successfully-applied */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* configuration-rejected-by-M-NG-RANNode */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* choice-extension */
};
asn_CHOICE_specifics_t asn_SPC_ResponseType_ReconfComplete_specs_1 = {
	sizeof(struct ResponseType_ReconfComplete),
	offsetof(struct ResponseType_ReconfComplete, _asn_ctx),
	offsetof(struct ResponseType_ReconfComplete, present),
	sizeof(((struct ResponseType_ReconfComplete *)0)->present),
	asn_MAP_ResponseType_ReconfComplete_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ResponseType_ReconfComplete = {
	"ResponseType-ReconfComplete",
	"ResponseType-ReconfComplete",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ResponseType_ReconfComplete_constr_1, CHOICE_constraint },
	asn_MBR_ResponseType_ReconfComplete_1,
	3,	/* Elements count */
	&asn_SPC_ResponseType_ReconfComplete_specs_1	/* Additional specs */
};

