/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_UEContextID_H_
#define	_UEContextID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_XNAP_UEContextID_PR {
    ASN_XNAP_UEContextID_PR_NOTHING,	/* No components present */
    ASN_XNAP_UEContextID_PR_rRCResume,
    ASN_XNAP_UEContextID_PR_rRRCReestablishment,
    ASN_XNAP_UEContextID_PR_choice_extension
} ASN_XNAP_UEContextID_PR;

/* Forward declarations */
struct ASN_XNAP_UEContextIDforRRCResume;
struct ASN_XNAP_UEContextIDforRRCReestablishment;
struct ASN_XNAP_ProtocolIE_Single_Container;

/* UEContextID */
typedef struct ASN_XNAP_UEContextID {
    ASN_XNAP_UEContextID_PR present;
	union ASN_XNAP_UEContextID_u {
		struct ASN_XNAP_UEContextIDforRRCResume	*rRCResume;
		struct ASN_XNAP_UEContextIDforRRCReestablishment	*rRRCReestablishment;
		struct ASN_XNAP_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_UEContextID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEContextID;

#ifdef __cplusplus
}
#endif

#endif	/* _UEContextID_H_ */
#include <asn_internal.h>
