/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_MaxIPrate_H_
#define	_MaxIPrate_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MaxIPrate {
	MaxIPrate_bitrate64kbs	= 0,
	MaxIPrate_max_UErate	= 1
	/*
	 * Enumeration is extensible
	 */
} e_MaxIPrate;

/* MaxIPrate */
typedef long	 MaxIPrate_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MaxIPrate_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MaxIPrate;
extern const asn_INTEGER_specifics_t asn_SPC_MaxIPrate_specs_1;
asn_struct_free_f MaxIPrate_free;
asn_struct_print_f MaxIPrate_print;
asn_constr_check_f MaxIPrate_constraint;
ber_type_decoder_f MaxIPrate_decode_ber;
der_type_encoder_f MaxIPrate_encode_der;
xer_type_decoder_f MaxIPrate_decode_xer;
xer_type_encoder_f MaxIPrate_encode_xer;
per_type_decoder_f MaxIPrate_decode_uper;
per_type_encoder_f MaxIPrate_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MaxIPrate_H_ */
#include <asn_internal.h>
