/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_SharedResourceType_ULDL_Sharing_DL_Resources_H_
#define	_SharedResourceType_ULDL_Sharing_DL_Resources_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SharedResourceType_ULDL_Sharing_DL_Resources_PR {
	SharedResourceType_ULDL_Sharing_DL_Resources_PR_NOTHING,	/* No components present */
	SharedResourceType_ULDL_Sharing_DL_Resources_PR_unchanged,
	SharedResourceType_ULDL_Sharing_DL_Resources_PR_changed,
	SharedResourceType_ULDL_Sharing_DL_Resources_PR_choice_extension
} SharedResourceType_ULDL_Sharing_DL_Resources_PR;

/* Forward declarations */
struct SharedResourceType_ULDL_Sharing_DL_ResourcesChanged;
struct ProtocolIE_Single_Container;

/* SharedResourceType-ULDL-Sharing-DL-Resources */
typedef struct SharedResourceType_ULDL_Sharing_DL_Resources {
	SharedResourceType_ULDL_Sharing_DL_Resources_PR present;
	union SharedResourceType_ULDL_Sharing_DL_Resources_u {
		NULL_t	 unchanged;
		struct SharedResourceType_ULDL_Sharing_DL_ResourcesChanged	*changed;
		struct ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SharedResourceType_ULDL_Sharing_DL_Resources_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SharedResourceType_ULDL_Sharing_DL_Resources;
extern asn_CHOICE_specifics_t asn_SPC_SharedResourceType_ULDL_Sharing_DL_Resources_specs_1;
extern asn_TYPE_member_t asn_MBR_SharedResourceType_ULDL_Sharing_DL_Resources_1[3];
extern asn_per_constraints_t asn_PER_type_SharedResourceType_ULDL_Sharing_DL_Resources_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SharedResourceType_ULDL_Sharing_DL_Resources_H_ */
#include <asn_internal.h>
