/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#include "UEContextID.h"

#include "UEContextIDforRRCResume.h"
#include "UEContextIDforRRCReestablishment.h"
#include "ProtocolIE-Single-Container.h"
static asn_per_constraints_t asn_PER_type_UEContextID_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_UEContextID_1[] = {
	{ ATF_POINTER, 0, offsetof(struct UEContextID, choice.rRCResume),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UEContextIDforRRCResume,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rRCResume"
		},
	{ ATF_POINTER, 0, offsetof(struct UEContextID, choice.rRRCReestablishment),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UEContextIDforRRCReestablishment,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rRRCReestablishment"
		},
	{ ATF_POINTER, 0, offsetof(struct UEContextID, choice.choice_extension),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolIE_Single_Container_5954P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"choice-extension"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_UEContextID_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rRCResume */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rRRCReestablishment */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* choice-extension */
};
static asn_CHOICE_specifics_t asn_SPC_UEContextID_specs_1 = {
	sizeof(struct UEContextID),
	offsetof(struct UEContextID, _asn_ctx),
	offsetof(struct UEContextID, present),
	sizeof(((struct UEContextID *)0)->present),
	asn_MAP_UEContextID_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_UEContextID = {
	"UEContextID",
	"UEContextID",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_UEContextID_constr_1, CHOICE_constraint },
	asn_MBR_UEContextID_1,
	3,	/* Elements count */
	&asn_SPC_UEContextID_specs_1	/* Additional specs */
};

