/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_E_UTRA_CGI_H_
#define	_E_UTRA_CGI_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMN-Identity.h"
#include "E-UTRA-Cell-Identity.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* E-UTRA-CGI */
typedef struct E_UTRA_CGI {
	PLMN_Identity_t	 plmn_id;
	E_UTRA_Cell_Identity_t	 e_utra_CI;
	struct ProtocolExtensionContainer	*iE_Extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E_UTRA_CGI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E_UTRA_CGI;
extern asn_SEQUENCE_specifics_t asn_SPC_E_UTRA_CGI_specs_1;
extern asn_TYPE_member_t asn_MBR_E_UTRA_CGI_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _E_UTRA_CGI_H_ */
#include <asn_internal.h>
