/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_NeighbourInformation_NR_ModeInfo_H_
#define	_NeighbourInformation_NR_ModeInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_XNAP_NeighbourInformation_NR_ModeInfo_PR {
    ASN_XNAP_NeighbourInformation_NR_ModeInfo_PR_NOTHING,	/* No components present */
    ASN_XNAP_NeighbourInformation_NR_ModeInfo_PR_fdd_info,
    ASN_XNAP_NeighbourInformation_NR_ModeInfo_PR_tdd_info,
    ASN_XNAP_NeighbourInformation_NR_ModeInfo_PR_choice_extension
} ASN_XNAP_NeighbourInformation_NR_ModeInfo_PR;

/* Forward declarations */
struct ASN_XNAP_NeighbourInformation_NR_ModeFDDInfo;
struct ASN_XNAP_NeighbourInformation_NR_ModeTDDInfo;
struct ASN_XNAP_ProtocolIE_Single_Container;

/* NeighbourInformation-NR-ModeInfo */
typedef struct ASN_XNAP_NeighbourInformation_NR_ModeInfo {
    ASN_XNAP_NeighbourInformation_NR_ModeInfo_PR present;
	union ASN_XNAP_NeighbourInformation_NR_ModeInfo_u {
		struct ASN_XNAP_NeighbourInformation_NR_ModeFDDInfo	*fdd_info;
		struct ASN_XNAP_NeighbourInformation_NR_ModeTDDInfo	*tdd_info;
		struct ASN_XNAP_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_NeighbourInformation_NR_ModeInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NeighbourInformation_NR_ModeInfo;
extern asn_CHOICE_specifics_t asn_SPC_NeighbourInformation_NR_ModeInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_NeighbourInformation_NR_ModeInfo_1[3];
extern asn_per_constraints_t asn_PER_type_NeighbourInformation_NR_ModeInfo_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NeighbourInformation_NR_ModeInfo_H_ */
#include <asn_internal.h>
