/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_NR_ResourceCoordinationInfo_H_
#define	_NR_ResourceCoordinationInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NR-CGI.h"
#include <BIT_STRING.h>
#include "NR-CoordinationAssistanceInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct E_UTRA_CGI;
struct ProtocolExtensionContainer;

/* NR-ResourceCoordinationInfo */
typedef struct NR_ResourceCoordinationInfo {
	NR_CGI_t	 nr_cell;
	BIT_STRING_t	 ul_coordination_info;
	BIT_STRING_t	*dl_coordination_info	/* OPTIONAL */;
	struct E_UTRA_CGI	*e_utra_cell	/* OPTIONAL */;
	NR_CoordinationAssistanceInfo_t	*nr_coordination_assistance_info	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NR_ResourceCoordinationInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NR_ResourceCoordinationInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_NR_ResourceCoordinationInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_NR_ResourceCoordinationInfo_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _NR_ResourceCoordinationInfo_H_ */
#include <asn_internal.h>
