/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_PDCPSNLength_H_
#define	_PDCPSNLength_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PDCPSNLength__ulPDCPSNLength {
	PDCPSNLength__ulPDCPSNLength_v12bits	= 0,
	PDCPSNLength__ulPDCPSNLength_v18bits	= 1
	/*
	 * Enumeration is extensible
	 */
} e_PDCPSNLength__ulPDCPSNLength;
typedef enum PDCPSNLength__dlPDCPSNLength {
	PDCPSNLength__dlPDCPSNLength_v12bits	= 0,
	PDCPSNLength__dlPDCPSNLength_v18bits	= 1
	/*
	 * Enumeration is extensible
	 */
} e_PDCPSNLength__dlPDCPSNLength;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* PDCPSNLength */
typedef struct PDCPSNLength {
	long	 ulPDCPSNLength;
	long	 dlPDCPSNLength;
	struct ProtocolExtensionContainer	*iE_Extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDCPSNLength_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ulPDCPSNLength_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_dlPDCPSNLength_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PDCPSNLength;
extern asn_SEQUENCE_specifics_t asn_SPC_PDCPSNLength_specs_1;
extern asn_TYPE_member_t asn_MBR_PDCPSNLength_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _PDCPSNLength_H_ */
#include <asn_internal.h>
