/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_ProtectedE_UTRAResourceList_H_
#define	_ProtectedE_UTRAResourceList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtectedE_UTRAResource_Item;

/* ProtectedE-UTRAResourceList */
typedef struct ProtectedE_UTRAResourceList {
	A_SEQUENCE_OF(struct ProtectedE_UTRAResource_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtectedE_UTRAResourceList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtectedE_UTRAResourceList;
extern asn_SET_OF_specifics_t asn_SPC_ProtectedE_UTRAResourceList_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtectedE_UTRAResourceList_1[1];
extern asn_per_constraints_t asn_PER_type_ProtectedE_UTRAResourceList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtectedE_UTRAResourceList_H_ */
#include <asn_internal.h>
