/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_ResetResponseTypeInfo_H_
#define	_ResetResponseTypeInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_XNAP_ResetResponseTypeInfo_PR {
	ResetResponseTypeInfo_PR_NOTHING,	/* No components present */
	ResetResponseTypeInfo_PR_fullReset,
	ResetResponseTypeInfo_PR_partialReset,
	ResetResponseTypeInfo_PR_choice_extension
} ASN_XNAP_ResetResponseTypeInfo_PR;

/* Forward declarations */
struct ASN_XNAP_ResetResponseTypeInfo_Full;
struct ASN_XNAP_ResetResponseTypeInfo_Partial;
struct ASN_XNAP_ProtocolIE_Single_Container;

/* ResetResponseTypeInfo */
typedef struct ASN_XNAP_ResetResponseTypeInfo {
    ASN_XNAP_ResetResponseTypeInfo_PR present;
	union ASN_XNAP_ResetResponseTypeInfo_u {
		struct ASN_XNAP_ResetResponseTypeInfo_Full	*fullReset;
		struct ASN_XNAP_ResetResponseTypeInfo_Partial	*partialReset;
		struct ASN_XNAP_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_ResetResponseTypeInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResetResponseTypeInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _ResetResponseTypeInfo_H_ */
#include <asn_internal.h>
