/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-PDU-Descriptions"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_UnsuccessfulOutcome_H_
#define	_UnsuccessfulOutcome_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_XNAP_ProcedureCode.h"
#include "ASN_XNAP_Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
//#include "HandoverRequest.h"
//#include "HandoverRequestAcknowledge.h"
//#include "HandoverPreparationFailure.h"
//#include "RetrieveUEContextRequest.h"
//#include "RetrieveUEContextResponse.h"
//#include "RetrieveUEContextFailure.h"
//#include "SNodeAdditionRequest.h"
//#include "SNodeAdditionRequestAcknowledge.h"
//#include "SNodeAdditionRequestReject.h"
//#include "SNodeModificationRequest.h"
//#include "SNodeModificationRequestAcknowledge.h"
//#include "SNodeModificationRequestReject.h"
//#include "SNodeModificationRequired.h"
//#include "SNodeModificationConfirm.h"
//#include "SNodeModificationRefuse.h"
//#include "SNodeReleaseRequest.h"
//#include "SNodeReleaseRequestAcknowledge.h"
//#include "SNodeReleaseReject.h"
//#include "SNodeReleaseRequired.h"
//#include "SNodeReleaseConfirm.h"
//#include "SNodeChangeRequired.h"
//#include "SNodeChangeConfirm.h"
//#include "SNodeChangeRefuse.h"
//#include "XnRemovalRequest.h"
//#include "XnRemovalResponse.h"
//#include "XnRemovalFailure.h"
#include "ASN_XNAP_XnSetupRequest.h"
#include "ASN_XNAP_XnSetupResponse.h"
#include "ASN_XNAP_XnSetupFailure.h"
//#include "NGRANNodeConfigurationUpdate.h"
//#include "NGRANNodeConfigurationUpdateAcknowledge.h"
//#include "NGRANNodeConfigurationUpdateFailure.h"
//#include "E-UTRA-NR-CellResourceCoordinationRequest.h"
//#include "E-UTRA-NR-CellResourceCoordinationResponse.h"
//#include "CellActivationRequest.h"
//#include "CellActivationResponse.h"
//#include "CellActivationFailure.h"
//#include "ResetRequest.h"
//#include "ResetResponse.h"
//#include "SNStatusTransfer.h"
//#include "HandoverCancel.h"
//#include "RANPaging.h"
//#include "XnUAddressIndication.h"
//#include "UEContextRelease.h"
//#include "SNodeReconfigurationComplete.h"
//#include "SNodeCounterCheckRequest.h"
//#include "RRCTransfer.h"
//#include "ErrorIndication.h"
//#include "PrivateMessage.h"
//#include "NotificationControlIndication.h"
//#include "ActivityNotification.h"
//#include "SecondaryRATDataUsageReport.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UnsuccessfulOutcome__value_PR {
	UnsuccessfulOutcome__value_PR_NOTHING,	/* No components present */
	UnsuccessfulOutcome__value_PR_HandoverPreparationFailure,
	UnsuccessfulOutcome__value_PR_RetrieveUEContextFailure,
	UnsuccessfulOutcome__value_PR_SNodeAdditionRequestReject,
	UnsuccessfulOutcome__value_PR_SNodeModificationRequestReject,
	UnsuccessfulOutcome__value_PR_SNodeModificationRefuse,
	UnsuccessfulOutcome__value_PR_SNodeReleaseReject,
	UnsuccessfulOutcome__value_PR_SNodeChangeRefuse,
	UnsuccessfulOutcome__value_PR_XnRemovalFailure,
	UnsuccessfulOutcome__value_PR_XnSetupFailure,
	UnsuccessfulOutcome__value_PR_NGRANNodeConfigurationUpdateFailure,
	UnsuccessfulOutcome__value_PR_CellActivationFailure
} UnsuccessfulOutcome__value_PR;

/* UnsuccessfulOutcome */
typedef struct UnsuccessfulOutcome {
	ProcedureCode_t	 procedureCode;
	Criticality_t	 criticality;
	struct UnsuccessfulOutcome__value {
		UnsuccessfulOutcome__value_PR present;
		union UnsuccessfulOutcome__value_u {
//			HandoverPreparationFailure_t	 HandoverPreparationFailure;
//			RetrieveUEContextFailure_t	 RetrieveUEContextFailure;
//			SNodeAdditionRequestReject_t	 SNodeAdditionRequestReject;
//			SNodeModificationRequestReject_t	 SNodeModificationRequestReject;
//			SNodeModificationRefuse_t	 SNodeModificationRefuse;
//			SNodeReleaseReject_t	 SNodeReleaseReject;
//			SNodeChangeRefuse_t	 SNodeChangeRefuse;
//			XnRemovalFailure_t	 XnRemovalFailure;
			XnSetupFailure_t	 XnSetupFailure;
//			NGRANNodeConfigurationUpdateFailure_t	 NGRANNodeConfigurationUpdateFailure;
//			CellActivationFailure_t	 CellActivationFailure;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UnsuccessfulOutcome_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UnsuccessfulOutcome;
extern asn_SEQUENCE_specifics_t asn_SPC_UnsuccessfulOutcome_specs_1;
extern asn_TYPE_member_t asn_MBR_UnsuccessfulOutcome_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _UnsuccessfulOutcome_H_ */
#include <asn_internal.h>
