/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_DRBBStatusTransfer18bitsSN_H_
#define	_DRBBStatusTransfer18bitsSN_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include "ASN_XNAP_COUNT-PDCP-SN18.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* DRBBStatusTransfer18bitsSN */
typedef struct DRBBStatusTransfer18bitsSN {
	BIT_STRING_t	*receiveStatusofPDCPSDU	/* OPTIONAL */;
	COUNT_PDCP_SN18_t	 cOUNTValue;
	struct ProtocolExtensionContainer	*iE_Extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DRBBStatusTransfer18bitsSN_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DRBBStatusTransfer18bitsSN;
extern asn_SEQUENCE_specifics_t asn_SPC_DRBBStatusTransfer18bitsSN_specs_1;
extern asn_TYPE_member_t asn_MBR_DRBBStatusTransfer18bitsSN_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _DRBBStatusTransfer18bitsSN_H_ */
#include <asn_internal.h>
