/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-PDU-Contents"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_Configuration_successfully_applied_H_
#define	_Configuration_successfully_applied_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* Configuration-successfully-applied */
typedef struct Configuration_successfully_applied {
	OCTET_STRING_t	*m_NG_RANNode_to_S_NG_RANNode_Container	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Configuration_successfully_applied_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Configuration_successfully_applied;
extern asn_SEQUENCE_specifics_t asn_SPC_Configuration_successfully_applied_specs_1;
extern asn_TYPE_member_t asn_MBR_Configuration_successfully_applied_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Configuration_successfully_applied_H_ */
#include <asn_internal.h>
