/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_RAT_RestrictionsItem_H_
#define	_RAT_RestrictionsItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMN-Identity.h"
#include "RAT-RestrictionInformation.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* RAT-RestrictionsItem */
typedef struct RAT_RestrictionsItem {
	PLMN_Identity_t	 plmn_Identity;
	RAT_RestrictionInformation_t	 rat_RestrictionInformation;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RAT_RestrictionsItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RAT_RestrictionsItem;
extern asn_SEQUENCE_specifics_t asn_SPC_RAT_RestrictionsItem_specs_1;
extern asn_TYPE_member_t asn_MBR_RAT_RestrictionsItem_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RAT_RestrictionsItem_H_ */
#include <asn_internal.h>
