/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_CyclicPrefix_E_UTRA_UL_H_
#define	_CyclicPrefix_E_UTRA_UL_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CyclicPrefix_E_UTRA_UL {
	CyclicPrefix_E_UTRA_UL_normal	= 0,
	CyclicPrefix_E_UTRA_UL_extended	= 1
	/*
	 * Enumeration is extensible
	 */
} e_CyclicPrefix_E_UTRA_UL;

/* CyclicPrefix-E-UTRA-UL */
typedef long	 CyclicPrefix_E_UTRA_UL_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CyclicPrefix_E_UTRA_UL_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CyclicPrefix_E_UTRA_UL;
extern const asn_INTEGER_specifics_t asn_SPC_CyclicPrefix_E_UTRA_UL_specs_1;
asn_struct_free_f CyclicPrefix_E_UTRA_UL_free;
asn_struct_print_f CyclicPrefix_E_UTRA_UL_print;
asn_constr_check_f CyclicPrefix_E_UTRA_UL_constraint;
ber_type_decoder_f CyclicPrefix_E_UTRA_UL_decode_ber;
der_type_encoder_f CyclicPrefix_E_UTRA_UL_encode_der;
xer_type_decoder_f CyclicPrefix_E_UTRA_UL_decode_xer;
xer_type_encoder_f CyclicPrefix_E_UTRA_UL_encode_xer;
per_type_decoder_f CyclicPrefix_E_UTRA_UL_decode_uper;
per_type_encoder_f CyclicPrefix_E_UTRA_UL_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CyclicPrefix_E_UTRA_UL_H_ */
#include <asn_internal.h>
