/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_ExpectedUEActivityBehaviour_H_
#define	_ExpectedUEActivityBehaviour_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_XNAP_ExpectedActivityPeriod.h"
#include "ASN_XNAP_ExpectedIdlePeriod.h"
#include "ASN_XNAP_SourceOfUEActivityBehaviourInformation.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASN_XNAP_ProtocolExtensionContainer;

/* ExpectedUEActivityBehaviour */
typedef struct ASN_XNAP_ExpectedUEActivityBehaviour {
    ASN_XNAP_ExpectedActivityPeriod_t	*expectedActivityPeriod	/* OPTIONAL */;
    ASN_XNAP_ExpectedIdlePeriod_t	*expectedIdlePeriod	/* OPTIONAL */;
    ASN_XNAP_SourceOfUEActivityBehaviourInformation_t	*sourceOfUEActivityBehaviourInformation	/* OPTIONAL */;
	struct ASN_XNAP_ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_ExpectedUEActivityBehaviour_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExpectedUEActivityBehaviour;
extern asn_SEQUENCE_specifics_t asn_SPC_ExpectedUEActivityBehaviour_specs_1;
extern asn_TYPE_member_t asn_MBR_ExpectedUEActivityBehaviour_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _ExpectedUEActivityBehaviour_H_ */
#include <asn_internal.h>
