/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-PDU-Contents"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_ResourceCoordRequest_gNB_initiated_H_
#define	_ResourceCoordRequest_gNB_initiated_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DataTrafficResourceIndication.h"
#include "SpectrumSharingGroupID.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;
struct E_UTRA_CGI;
struct NR_CGI;

/* ResourceCoordRequest-gNB-initiated */
typedef struct ResourceCoordRequest_gNB_initiated {
	DataTrafficResourceIndication_t	 dataTrafficResourceIndication;
	struct ResourceCoordRequest_gNB_initiated__listofE_UTRACells {
		A_SEQUENCE_OF(struct E_UTRA_CGI) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *listofE_UTRACells;
	SpectrumSharingGroupID_t	 spectrumSharingGroupID;
	struct ResourceCoordRequest_gNB_initiated__listofNRCells {
		A_SEQUENCE_OF(struct NR_CGI) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *listofNRCells;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResourceCoordRequest_gNB_initiated_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResourceCoordRequest_gNB_initiated;
extern asn_SEQUENCE_specifics_t asn_SPC_ResourceCoordRequest_gNB_initiated_specs_1;
extern asn_TYPE_member_t asn_MBR_ResourceCoordRequest_gNB_initiated_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _ResourceCoordRequest_gNB_initiated_H_ */
#include <asn_internal.h>
