/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_SharedResourceType_H_
#define	_SharedResourceType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SharedResourceType_PR {
	SharedResourceType_PR_NOTHING,	/* No components present */
	SharedResourceType_PR_ul_onlySharing,
	SharedResourceType_PR_ul_and_dl_Sharing,
	SharedResourceType_PR_choice_extension
} SharedResourceType_PR;

/* Forward declarations */
struct SharedResourceType_UL_OnlySharing;
struct SharedResourceType_ULDL_Sharing;
struct ProtocolIE_Single_Container;

/* SharedResourceType */
typedef struct SharedResourceType {
	SharedResourceType_PR present;
	union SharedResourceType_u {
		struct SharedResourceType_UL_OnlySharing	*ul_onlySharing;
		struct SharedResourceType_ULDL_Sharing	*ul_and_dl_Sharing;
		struct ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SharedResourceType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SharedResourceType;
extern asn_CHOICE_specifics_t asn_SPC_SharedResourceType_specs_1;
extern asn_TYPE_member_t asn_MBR_SharedResourceType_1[3];
extern asn_per_constraints_t asn_PER_type_SharedResourceType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SharedResourceType_H_ */
#include <asn_internal.h>
