/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_PDUSessionResourcesToBeSetup_Item_H_
#define	_PDUSessionResourcesToBeSetup_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PDUSession-ID.h"
#include "S-NSSAI.h"
#include "UPTransportLayerInformation.h"
#include "PDUSessionType.h"
#include "PDUSessionNetworkInstance.h"
#include "QoSFlowsToBeSetup-List.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PDUSessionAggregateMaximumBitRate;
struct UPTransportLayerInformation;
struct SecurityIndication;
struct DataforwardingandOffloadingInfofromSource;
struct ProtocolExtensionContainer;

/* PDUSessionResourcesToBeSetup-Item */
typedef struct PDUSessionResourcesToBeSetup_Item {
	PDUSession_ID_t	 pduSessionId;
	S_NSSAI_t	 s_NSSAI;
	struct PDUSessionAggregateMaximumBitRate	*pduSessionAMBR	/* OPTIONAL */;
	UPTransportLayerInformation_t	 uL_NG_U_TNLatUPF;
	struct UPTransportLayerInformation	*source_DL_NG_U_TNL_Information	/* OPTIONAL */;
	struct SecurityIndication	*securityIndication	/* OPTIONAL */;
	PDUSessionType_t	 pduSessionType;
	PDUSessionNetworkInstance_t	*pduSessionNetworkInstance	/* OPTIONAL */;
	QoSFlowsToBeSetup_List_t	 qosFlowsToBeSetup_List;
	struct DataforwardingandOffloadingInfofromSource	*dataforwardinginfofromSource	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDUSessionResourcesToBeSetup_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDUSessionResourcesToBeSetup_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_PDUSessionResourcesToBeSetup_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_PDUSessionResourcesToBeSetup_Item_1[11];

#ifdef __cplusplus
}
#endif

#endif	/* _PDUSessionResourcesToBeSetup_Item_H_ */
#include <asn_internal.h>
