/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-PDU-Contents"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_InitiatingNodeType_ResourceCoordRequest_H_
#define	_InitiatingNodeType_ResourceCoordRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum InitiatingNodeType_ResourceCoordRequest_PR {
	InitiatingNodeType_ResourceCoordRequest_PR_NOTHING,	/* No components present */
	InitiatingNodeType_ResourceCoordRequest_PR_ng_eNB,
	InitiatingNodeType_ResourceCoordRequest_PR_gNB,
	InitiatingNodeType_ResourceCoordRequest_PR_choice_extension
} InitiatingNodeType_ResourceCoordRequest_PR;

/* Forward declarations */
struct ResourceCoordRequest_ng_eNB_initiated;
struct ResourceCoordRequest_gNB_initiated;
struct ProtocolIE_Single_Container;

/* InitiatingNodeType-ResourceCoordRequest */
typedef struct InitiatingNodeType_ResourceCoordRequest {
	InitiatingNodeType_ResourceCoordRequest_PR present;
	union InitiatingNodeType_ResourceCoordRequest_u {
		struct ResourceCoordRequest_ng_eNB_initiated	*ng_eNB;
		struct ResourceCoordRequest_gNB_initiated	*gNB;
		struct ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InitiatingNodeType_ResourceCoordRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InitiatingNodeType_ResourceCoordRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _InitiatingNodeType_ResourceCoordRequest_H_ */
#include <asn_internal.h>
