/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_NG_RAN_Node_ResourceCoordinationInfo_H_
#define	_NG_RAN_Node_ResourceCoordinationInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NG_RAN_Node_ResourceCoordinationInfo_PR {
	NG_RAN_Node_ResourceCoordinationInfo_PR_NOTHING,	/* No components present */
	NG_RAN_Node_ResourceCoordinationInfo_PR_eutra_resource_coordination_info,
	NG_RAN_Node_ResourceCoordinationInfo_PR_nr_resource_coordination_info
} NG_RAN_Node_ResourceCoordinationInfo_PR;

/* Forward declarations */
struct E_UTRA_ResourceCoordinationInfo;
struct NR_ResourceCoordinationInfo;

/* NG-RAN-Node-ResourceCoordinationInfo */
typedef struct NG_RAN_Node_ResourceCoordinationInfo {
	NG_RAN_Node_ResourceCoordinationInfo_PR present;
	union NG_RAN_Node_ResourceCoordinationInfo_u {
		struct E_UTRA_ResourceCoordinationInfo	*eutra_resource_coordination_info;
		struct NR_ResourceCoordinationInfo	*nr_resource_coordination_info;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NG_RAN_Node_ResourceCoordinationInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NG_RAN_Node_ResourceCoordinationInfo;
extern asn_CHOICE_specifics_t asn_SPC_NG_RAN_Node_ResourceCoordinationInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_NG_RAN_Node_ResourceCoordinationInfo_1[2];
extern asn_per_constraints_t asn_PER_type_NG_RAN_Node_ResourceCoordinationInfo_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NG_RAN_Node_ResourceCoordinationInfo_H_ */
#include <asn_internal.h>
