/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_LocationReportingInformation_H_
#define	_LocationReportingInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EventType.h"
#include "ReportArea.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AreaOfInterestInformation;
struct ProtocolExtensionContainer;

/* LocationReportingInformation */
typedef struct LocationReportingInformation {
	EventType_t	 eventType;
	ReportArea_t	 reportArea;
	struct AreaOfInterestInformation	*areaOfInterest	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LocationReportingInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LocationReportingInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_LocationReportingInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_LocationReportingInformation_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _LocationReportingInformation_H_ */
#include <asn_internal.h>
