/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_PDUSessionResourceModRqdInfo_MNterminated_H_
#define	_PDUSessionResourceModRqdInfo_MNterminated_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DRBsToBeModified_List_ModRqd_MNterminated;
struct DRB_List_withCause;
struct ProtocolExtensionContainer;

/* PDUSessionResourceModRqdInfo-MNterminated */
typedef struct PDUSessionResourceModRqdInfo_MNterminated {
	struct DRBsToBeModified_List_ModRqd_MNterminated	*dRBsToBeModified	/* OPTIONAL */;
	struct DRB_List_withCause	*dRBsToBeReleased	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDUSessionResourceModRqdInfo_MNterminated_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDUSessionResourceModRqdInfo_MNterminated;
extern asn_SEQUENCE_specifics_t asn_SPC_PDUSessionResourceModRqdInfo_MNterminated_specs_1;
extern asn_TYPE_member_t asn_MBR_PDUSessionResourceModRqdInfo_MNterminated_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _PDUSessionResourceModRqdInfo_MNterminated_H_ */
#include <asn_internal.h>
