/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_Target_CGI_H_
#define	_Target_CGI_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_XNAP_Target_CGI_PR {
    ASN_XNAP_Target_CGI_PR_NOTHING,	/* No components present */
    ASN_XNAP_Target_CGI_PR_nr,
    ASN_XNAP_Target_CGI_PR_e_utra,
    ASN_XNAP_Target_CGI_PR_choice_extension
} ASN_XNAP_Target_CGI_PR;

/* Forward declarations */
struct ASN_XNAP_NR_CGI;
struct ASN_XNAP_E_UTRA_CGI;
struct ASN_XNAP_ProtocolIE_Single_Container;

/* Target-CGI */
typedef struct ASN_XNAP_Target_CGI {
    ASN_XNAP_Target_CGI_PR present;
	union ASN_XNAP_Target_CGI_u {
		struct ASN_XNAP_NR_CGI	*nr;
		struct ASN_XNAP_E_UTRA_CGI	*e_utra;
		struct ASN_XNAP_ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_Target_CGI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Target_CGI;

#ifdef __cplusplus
}
#endif

#endif	/* _Target_CGI_H_ */
#include <asn_internal.h>
