/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_DefaultDRB_Allowed_H_
#define	_DefaultDRB_Allowed_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DefaultDRB_Allowed {
	DefaultDRB_Allowed_true	= 0,
	DefaultDRB_Allowed_false	= 1
	/*
	 * Enumeration is extensible
	 */
} e_DefaultDRB_Allowed;

/* DefaultDRB-Allowed */
typedef long	 DefaultDRB_Allowed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DefaultDRB_Allowed;
asn_struct_free_f DefaultDRB_Allowed_free;
asn_struct_print_f DefaultDRB_Allowed_print;
asn_constr_check_f DefaultDRB_Allowed_constraint;
ber_type_decoder_f DefaultDRB_Allowed_decode_ber;
der_type_encoder_f DefaultDRB_Allowed_encode_der;
xer_type_decoder_f DefaultDRB_Allowed_decode_xer;
xer_type_encoder_f DefaultDRB_Allowed_encode_xer;
per_type_decoder_f DefaultDRB_Allowed_decode_uper;
per_type_encoder_f DefaultDRB_Allowed_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DefaultDRB_Allowed_H_ */
#include <asn_internal.h>
