/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_DataforwardingandOffloadingInfofromSource_H_
#define	_DataforwardingandOffloadingInfofromSource_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_XNAP_QoSFLowsToBeForwarded-List.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DRBToQoSFlowMapping_List;
struct ProtocolExtensionContainer;

/* DataforwardingandOffloadingInfofromSource */
typedef struct DataforwardingandOffloadingInfofromSource {
	QoSFLowsToBeForwarded_List_t	 qosFlowsToBeForwarded;
	struct DRBToQoSFlowMapping_List	*sourceDRBtoQoSFlowMapping	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DataforwardingandOffloadingInfofromSource_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataforwardingandOffloadingInfofromSource;
extern asn_SEQUENCE_specifics_t asn_SPC_DataforwardingandOffloadingInfofromSource_specs_1;
extern asn_TYPE_member_t asn_MBR_DataforwardingandOffloadingInfofromSource_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _DataforwardingandOffloadingInfofromSource_H_ */
#include <asn_internal.h>
