/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_NeighbourInformation_E_UTRA_Item_H_
#define	_NeighbourInformation_E_UTRA_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "E-UTRAPCI.h"
#include "E-UTRA-CGI.h"
#include "E-UTRAARFCN.h"
#include "TAC.h"
#include "RANAC.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* NeighbourInformation-E-UTRA-Item */
typedef struct NeighbourInformation_E_UTRA_Item {
	E_UTRAPCI_t	 e_utra_PCI;
	E_UTRA_CGI_t	 e_utra_cgi;
	E_UTRAARFCN_t	 earfcn;
	TAC_t	 tac;
	RANAC_t	*ranac	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NeighbourInformation_E_UTRA_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NeighbourInformation_E_UTRA_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_NeighbourInformation_E_UTRA_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NeighbourInformation_E_UTRA_Item_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _NeighbourInformation_E_UTRA_Item_H_ */
#include <asn_internal.h>
