/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-PDU-Contents"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#include "UEContextRefAtSN-HORequest.h"

#include "ProtocolExtensionContainer.h"
static asn_TYPE_member_t asn_MBR_UEContextRefAtSN_HORequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UEContextRefAtSN_HORequest, globalNG_RANNode_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GlobalNG_RANNode_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"globalNG-RANNode-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct UEContextRefAtSN_HORequest, sN_NG_RANnodeUEXnAPID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NG_RANnodeUEXnAPID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sN-NG-RANnodeUEXnAPID"
		},
	{ ATF_POINTER, 1, offsetof(struct UEContextRefAtSN_HORequest, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_6001P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_UEContextRefAtSN_HORequest_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_UEContextRefAtSN_HORequest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UEContextRefAtSN_HORequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* globalNG-RANNode-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sN-NG-RANnodeUEXnAPID */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_UEContextRefAtSN_HORequest_specs_1 = {
	sizeof(struct UEContextRefAtSN_HORequest),
	offsetof(struct UEContextRefAtSN_HORequest, _asn_ctx),
	asn_MAP_UEContextRefAtSN_HORequest_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_UEContextRefAtSN_HORequest_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UEContextRefAtSN_HORequest = {
	"UEContextRefAtSN-HORequest",
	"UEContextRefAtSN-HORequest",
	&asn_OP_SEQUENCE,
	asn_DEF_UEContextRefAtSN_HORequest_tags_1,
	sizeof(asn_DEF_UEContextRefAtSN_HORequest_tags_1)
		/sizeof(asn_DEF_UEContextRefAtSN_HORequest_tags_1[0]), /* 1 */
	asn_DEF_UEContextRefAtSN_HORequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_UEContextRefAtSN_HORequest_tags_1)
		/sizeof(asn_DEF_UEContextRefAtSN_HORequest_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_UEContextRefAtSN_HORequest_1,
	3,	/* Elements count */
	&asn_SPC_UEContextRefAtSN_HORequest_specs_1	/* Additional specs */
};

