/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-PDU-Contents"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_PDUSessionAdmitted_SNModResponse_H_
#define	_PDUSessionAdmitted_SNModResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PDUSessionAdmittedToBeAddedSNModResponse;
struct PDUSessionAdmittedToBeModifiedSNModResponse;
struct PDUSessionAdmittedToBeReleasedSNModResponse;
struct ProtocolExtensionContainer;

/* PDUSessionAdmitted-SNModResponse */
typedef struct PDUSessionAdmitted_SNModResponse {
	struct PDUSessionAdmittedToBeAddedSNModResponse	*pduSessionResourcesAdmittedToBeAdded	/* OPTIONAL */;
	struct PDUSessionAdmittedToBeModifiedSNModResponse	*pduSessionResourcesAdmittedToBeModified	/* OPTIONAL */;
	struct PDUSessionAdmittedToBeReleasedSNModResponse	*pduSessionResourcesAdmittedToBeReleased	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDUSessionAdmitted_SNModResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDUSessionAdmitted_SNModResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _PDUSessionAdmitted_SNModResponse_H_ */
#include <asn_internal.h>
