/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_DataForwardingInfoFromTargetNGRANnode_H_
#define	_DataForwardingInfoFromTargetNGRANnode_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_XNAP_QoSFLowsAcceptedToBeForwarded-List.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UPTransportLayerInformation;
struct DataForwardingResponseDRBItemList;
struct ProtocolExtensionContainer;

/* DataForwardingInfoFromTargetNGRANnode */
typedef struct DataForwardingInfoFromTargetNGRANnode {
	QoSFLowsAcceptedToBeForwarded_List_t	 qosFlowsAcceptedForDataForwarding_List;
	struct UPTransportLayerInformation	*pduSessionLevelDLDataForwardingInfo	/* OPTIONAL */;
	struct UPTransportLayerInformation	*pduSessionLevelULDataForwardingInfo	/* OPTIONAL */;
	struct DataForwardingResponseDRBItemList	*dataForwardingResponseDRBItemList	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DataForwardingInfoFromTargetNGRANnode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataForwardingInfoFromTargetNGRANnode;
extern asn_SEQUENCE_specifics_t asn_SPC_DataForwardingInfoFromTargetNGRANnode_specs_1;
extern asn_TYPE_member_t asn_MBR_DataForwardingInfoFromTargetNGRANnode_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _DataForwardingInfoFromTargetNGRANnode_H_ */
#include <asn_internal.h>
