/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-PDU-Contents"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_PDUSessionNotAdmitted_SNModResponse_H_
#define	_PDUSessionNotAdmitted_SNModResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PDUSession_List;
struct ProtocolExtensionContainer;

/* PDUSessionNotAdmitted-SNModResponse */
typedef struct PDUSessionNotAdmitted_SNModResponse {
	struct PDUSession_List	*pdu_Session_List	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDUSessionNotAdmitted_SNModResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDUSessionNotAdmitted_SNModResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _PDUSessionNotAdmitted_SNModResponse_H_ */
#include <asn_internal.h>
