/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_NeighbourInformation_NR_Item_H_
#define	_NeighbourInformation_NR_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPCI.h"
#include "NR-CGI.h"
#include "TAC.h"
#include "RANAC.h"
#include "NeighbourInformation-NR-ModeInfo.h"
#include "Connectivity-Support.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* NeighbourInformation-NR-Item */
typedef struct NeighbourInformation_NR_Item {
	NRPCI_t	 nr_PCI;
	NR_CGI_t	 nr_cgi;
	TAC_t	 tac;
	RANAC_t	*ranac	/* OPTIONAL */;
	NeighbourInformation_NR_ModeInfo_t	 nr_mode_info;
	Connectivity_Support_t	 connectivitySupport;
	OCTET_STRING_t	 measurementTimingConfiguration;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NeighbourInformation_NR_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NeighbourInformation_NR_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_NeighbourInformation_NR_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NeighbourInformation_NR_Item_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _NeighbourInformation_NR_Item_H_ */
#include <asn_internal.h>
