/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_BPLMN_ID_Info_EUTRA_H_
#define	_BPLMN_ID_Info_EUTRA_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BPLMN_ID_Info_EUTRA_Item;

/* BPLMN-ID-Info-EUTRA */
typedef struct BPLMN_ID_Info_EUTRA {
	A_SEQUENCE_OF(struct BPLMN_ID_Info_EUTRA_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BPLMN_ID_Info_EUTRA_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BPLMN_ID_Info_EUTRA;

#ifdef __cplusplus
}
#endif

#endif	/* _BPLMN_ID_Info_EUTRA_H_ */
#include <asn_internal.h>
