/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_UEContextIDforRRCReestablishment_H_
#define	_UEContextIDforRRCReestablishment_H_


#include <asn_application.h>

/* Including external dependencies */
#include "C-RNTI.h"
#include "NG-RAN-CellPCI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* UEContextIDforRRCReestablishment */
typedef struct UEContextIDforRRCReestablishment {
	C_RNTI_t	 c_rnti;
	NG_RAN_CellPCI_t	 failureCellPCI;
	struct ProtocolExtensionContainer	*iE_Extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEContextIDforRRCReestablishment_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEContextIDforRRCReestablishment;
extern asn_SEQUENCE_specifics_t asn_SPC_UEContextIDforRRCReestablishment_specs_1;
extern asn_TYPE_member_t asn_MBR_UEContextIDforRRCReestablishment_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _UEContextIDforRRCReestablishment_H_ */
#include <asn_internal.h>
