/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_SharedResourceType_ULDL_Sharing_DL_ResourcesChanged_H_
#define	_SharedResourceType_ULDL_Sharing_DL_ResourcesChanged_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DataTrafficResources.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* SharedResourceType-ULDL-Sharing-DL-ResourcesChanged */
typedef struct SharedResourceType_ULDL_Sharing_DL_ResourcesChanged {
	DataTrafficResources_t	 dl_resourceBitmap;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SharedResourceType_ULDL_Sharing_DL_ResourcesChanged_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SharedResourceType_ULDL_Sharing_DL_ResourcesChanged;
extern asn_SEQUENCE_specifics_t asn_SPC_SharedResourceType_ULDL_Sharing_DL_ResourcesChanged_specs_1;
extern asn_TYPE_member_t asn_MBR_SharedResourceType_ULDL_Sharing_DL_ResourcesChanged_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SharedResourceType_ULDL_Sharing_DL_ResourcesChanged_H_ */
#include <asn_internal.h>
