/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_S_NG_RANnode_Addition_Trigger_Ind_H_
#define	_S_NG_RANnode_Addition_Trigger_Ind_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum S_NG_RANnode_Addition_Trigger_Ind {
	S_NG_RANnode_Addition_Trigger_Ind_sn_change	= 0,
	S_NG_RANnode_Addition_Trigger_Ind_inter_MN_HO	= 1,
	S_NG_RANnode_Addition_Trigger_Ind_intra_MN_HO	= 2
	/*
	 * Enumeration is extensible
	 */
} e_S_NG_RANnode_Addition_Trigger_Ind;

/* S-NG-RANnode-Addition-Trigger-Ind */
typedef long	 S_NG_RANnode_Addition_Trigger_Ind_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S_NG_RANnode_Addition_Trigger_Ind;
asn_struct_free_f S_NG_RANnode_Addition_Trigger_Ind_free;
asn_struct_print_f S_NG_RANnode_Addition_Trigger_Ind_print;
asn_constr_check_f S_NG_RANnode_Addition_Trigger_Ind_constraint;
ber_type_decoder_f S_NG_RANnode_Addition_Trigger_Ind_decode_ber;
der_type_encoder_f S_NG_RANnode_Addition_Trigger_Ind_encode_der;
xer_type_decoder_f S_NG_RANnode_Addition_Trigger_Ind_decode_xer;
xer_type_encoder_f S_NG_RANnode_Addition_Trigger_Ind_encode_xer;
per_type_decoder_f S_NG_RANnode_Addition_Trigger_Ind_decode_uper;
per_type_encoder_f S_NG_RANnode_Addition_Trigger_Ind_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _S_NG_RANnode_Addition_Trigger_Ind_H_ */
#include <asn_internal.h>
