/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_MR_DC_ResourceCoordinationInfo_H_
#define	_MR_DC_ResourceCoordinationInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_XNAP_NG-RAN-Node-ResourceCoordinationInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASN_XNAP_ProtocolExtensionContainer;

/* MR-DC-ResourceCoordinationInfo */
typedef struct ASN_XNAP_MR_DC_ResourceCoordinationInfo {
    ASN_XNAP_NG_RAN_Node_ResourceCoordinationInfo_t	 ng_RAN_Node_ResourceCoordinationInfo;
	struct ASN_XNAP_ProtocolExtensionContainer	*iE_Extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_MR_DC_ResourceCoordinationInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MR_DC_ResourceCoordinationInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _MR_DC_ResourceCoordinationInfo_H_ */
#include <asn_internal.h>
