/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_DRBBStatusTransferChoice_H_
#define	_DRBBStatusTransferChoice_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DRBBStatusTransferChoice_PR {
	DRBBStatusTransferChoice_PR_NOTHING,	/* No components present */
	DRBBStatusTransferChoice_PR_pdcp_sn_12bits,
	DRBBStatusTransferChoice_PR_pdcp_sn_18bits,
	DRBBStatusTransferChoice_PR_choice_extension
} DRBBStatusTransferChoice_PR;

/* Forward declarations */
struct DRBBStatusTransfer12bitsSN;
struct DRBBStatusTransfer18bitsSN;
struct ProtocolIE_Single_Container;

/* DRBBStatusTransferChoice */
typedef struct DRBBStatusTransferChoice {
	DRBBStatusTransferChoice_PR present;
	union DRBBStatusTransferChoice_u {
		struct DRBBStatusTransfer12bitsSN	*pdcp_sn_12bits;
		struct DRBBStatusTransfer18bitsSN	*pdcp_sn_18bits;
		struct ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DRBBStatusTransferChoice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DRBBStatusTransferChoice;
extern asn_CHOICE_specifics_t asn_SPC_DRBBStatusTransferChoice_specs_1;
extern asn_TYPE_member_t asn_MBR_DRBBStatusTransferChoice_1[3];
extern asn_per_constraints_t asn_PER_type_DRBBStatusTransferChoice_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _DRBBStatusTransferChoice_H_ */
#include <asn_internal.h>
