/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_MBSFNSubframeInfo_E_UTRA_Item_H_
#define	_MBSFNSubframeInfo_E_UTRA_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include "MBSFNSubframeAllocation-E-UTRA.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MBSFNSubframeInfo_E_UTRA_Item__radioframeAllocationPeriod {
	MBSFNSubframeInfo_E_UTRA_Item__radioframeAllocationPeriod_n1	= 0,
	MBSFNSubframeInfo_E_UTRA_Item__radioframeAllocationPeriod_n2	= 1,
	MBSFNSubframeInfo_E_UTRA_Item__radioframeAllocationPeriod_n4	= 2,
	MBSFNSubframeInfo_E_UTRA_Item__radioframeAllocationPeriod_n8	= 3,
	MBSFNSubframeInfo_E_UTRA_Item__radioframeAllocationPeriod_n16	= 4,
	MBSFNSubframeInfo_E_UTRA_Item__radioframeAllocationPeriod_n32	= 5
	/*
	 * Enumeration is extensible
	 */
} e_MBSFNSubframeInfo_E_UTRA_Item__radioframeAllocationPeriod;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* MBSFNSubframeInfo-E-UTRA-Item */
typedef struct MBSFNSubframeInfo_E_UTRA_Item {
	long	 radioframeAllocationPeriod;
	long	 radioframeAllocationOffset;
	MBSFNSubframeAllocation_E_UTRA_t	 subframeAllocation;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBSFNSubframeInfo_E_UTRA_Item_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_radioframeAllocationPeriod_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MBSFNSubframeInfo_E_UTRA_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_MBSFNSubframeInfo_E_UTRA_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_MBSFNSubframeInfo_E_UTRA_Item_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _MBSFNSubframeInfo_E_UTRA_Item_H_ */
#include <asn_internal.h>
