/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_RAT_RestrictionInformation_H_
#define	_RAT_RestrictionInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASN_XNAP_RAT_RestrictionInformation {
    ASN_XNAP_RAT_RestrictionInformation_e_UTRA	= 0,
    ASN_XNAP_RAT_RestrictionInformation_nR	= 1
} e_ASN_XNAP_RAT_RestrictionInformation;

/* RAT-RestrictionInformation */
typedef BIT_STRING_t	 ASN_XNAP_RAT_RestrictionInformation_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RAT_RestrictionInformation_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RAT_RestrictionInformation;
asn_struct_free_f RAT_RestrictionInformation_free;
asn_struct_print_f RAT_RestrictionInformation_print;
asn_constr_check_f RAT_RestrictionInformation_constraint;
ber_type_decoder_f RAT_RestrictionInformation_decode_ber;
der_type_encoder_f RAT_RestrictionInformation_encode_der;
xer_type_decoder_f RAT_RestrictionInformation_decode_xer;
xer_type_encoder_f RAT_RestrictionInformation_encode_xer;
per_type_decoder_f RAT_RestrictionInformation_decode_uper;
per_type_encoder_f RAT_RestrictionInformation_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RAT_RestrictionInformation_H_ */
#include <asn_internal.h>
