/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_PDUSessionResourceSetupInfo_SNterminated_H_
#define	_PDUSessionResourceSetupInfo_SNterminated_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UPTransportLayerInformation.h"
#include "PDUSessionType.h"
#include "PDUSessionNetworkInstance.h"
#include "QoSFlowsToBeSetup-List-Setup-SNterminated.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DataforwardingandOffloadingInfofromSource;
struct SecurityIndication;
struct ProtocolExtensionContainer;

/* PDUSessionResourceSetupInfo-SNterminated */
typedef struct PDUSessionResourceSetupInfo_SNterminated {
	UPTransportLayerInformation_t	 uL_NG_U_TNLatUPF;
	PDUSessionType_t	 pduSessionType;
	PDUSessionNetworkInstance_t	*pduSessionNetworkInstance	/* OPTIONAL */;
	QoSFlowsToBeSetup_List_Setup_SNterminated_t	 qosFlowsToBeSetup_List;
	struct DataforwardingandOffloadingInfofromSource	*dataforwardinginfofromSource	/* OPTIONAL */;
	struct SecurityIndication	*securityIndication	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDUSessionResourceSetupInfo_SNterminated_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDUSessionResourceSetupInfo_SNterminated;
extern asn_SEQUENCE_specifics_t asn_SPC_PDUSessionResourceSetupInfo_SNterminated_specs_1;
extern asn_TYPE_member_t asn_MBR_PDUSessionResourceSetupInfo_SNterminated_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _PDUSessionResourceSetupInfo_SNterminated_H_ */
#include <asn_internal.h>
