/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_NE_DC_TDM_Pattern_H_
#define	_NE_DC_TDM_Pattern_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NE_DC_TDM_Pattern__subframeAssignment {
	NE_DC_TDM_Pattern__subframeAssignment_sa0	= 0,
	NE_DC_TDM_Pattern__subframeAssignment_sa1	= 1,
	NE_DC_TDM_Pattern__subframeAssignment_sa2	= 2,
	NE_DC_TDM_Pattern__subframeAssignment_sa3	= 3,
	NE_DC_TDM_Pattern__subframeAssignment_sa4	= 4,
	NE_DC_TDM_Pattern__subframeAssignment_sa5	= 5,
	NE_DC_TDM_Pattern__subframeAssignment_sa6	= 6
} e_NE_DC_TDM_Pattern__subframeAssignment;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* NE-DC-TDM-Pattern */
typedef struct NE_DC_TDM_Pattern {
	long	 subframeAssignment;
	long	 harqOffset;
	struct ProtocolExtensionContainer	*iE_Extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NE_DC_TDM_Pattern_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_subframeAssignment_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NE_DC_TDM_Pattern;

#ifdef __cplusplus
}
#endif

#endif	/* _NE_DC_TDM_Pattern_H_ */
#include <asn_internal.h>
