/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_ProtectedE_UTRAResourceIndication_H_
#define	_ProtectedE_UTRAResourceIndication_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_XNAP_ActivationSFN.h"
#include "ProtectedE-UTRAResourceList.h"
#include "MBSFNControlRegionLength.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* ProtectedE-UTRAResourceIndication */
typedef struct ProtectedE_UTRAResourceIndication {
	ActivationSFN_t	 activationSFN;
	ProtectedE_UTRAResourceList_t	 protectedResourceList;
	MBSFNControlRegionLength_t	*mbsfnControlRegionLength	/* OPTIONAL */;
	long	 pDCCHRegionLength;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtectedE_UTRAResourceIndication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtectedE_UTRAResourceIndication;
extern asn_SEQUENCE_specifics_t asn_SPC_ProtectedE_UTRAResourceIndication_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtectedE_UTRAResourceIndication_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _ProtectedE_UTRAResourceIndication_H_ */
#include <asn_internal.h>
