/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_DRBsToBeSetupList_SetupResponse_SNterminated_Item_H_
#define	_DRBsToBeSetupList_SetupResponse_SNterminated_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DRB-ID.h"
#include "UPTransportParameters.h"
#include "QoSFlowLevelQoSParameters.h"
#include "RLCMode.h"
#include "DuplicationActivation.h"
#include "QoSFlowsMappedtoDRB-SetupResponse-SNterminated.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PDCPSNLength;
struct ULConfiguration;
struct UPTransportParameters;
struct ProtocolExtensionContainer;

/* DRBsToBeSetupList-SetupResponse-SNterminated-Item */
typedef struct DRBsToBeSetupList_SetupResponse_SNterminated_Item {
	DRB_ID_t	 drb_ID;
	UPTransportParameters_t	 sN_UL_PDCP_UP_TNLInfo;
	QoSFlowLevelQoSParameters_t	 dRB_QoS;
	struct PDCPSNLength	*pDCP_SNLength	/* OPTIONAL */;
	RLCMode_t	 rLC_Mode;
	struct ULConfiguration	*uL_Configuration	/* OPTIONAL */;
	struct UPTransportParameters	*secondary_SN_UL_PDCP_UP_TNLInfo	/* OPTIONAL */;
	DuplicationActivation_t	*duplicationActivation	/* OPTIONAL */;
	QoSFlowsMappedtoDRB_SetupResponse_SNterminated_t	 qoSFlowsMappedtoDRB_SetupResponse_SNterminated;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DRBsToBeSetupList_SetupResponse_SNterminated_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DRBsToBeSetupList_SetupResponse_SNterminated_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_DRBsToBeSetupList_SetupResponse_SNterminated_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_DRBsToBeSetupList_SetupResponse_SNterminated_Item_1[10];

#ifdef __cplusplus
}
#endif

#endif	/* _DRBsToBeSetupList_SetupResponse_SNterminated_Item_H_ */
#include <asn_internal.h>
