/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_BroadcastPLMNinTAISupport_Item_H_
#define	_BroadcastPLMNinTAISupport_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMN-Identity.h"
#include "SliceSupport-List.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* BroadcastPLMNinTAISupport-Item */
typedef struct BroadcastPLMNinTAISupport_Item {
	PLMN_Identity_t	 plmn_id;
	SliceSupport_List_t	 tAISliceSupport_List;
	struct ProtocolExtensionContainer	*iE_Extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BroadcastPLMNinTAISupport_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BroadcastPLMNinTAISupport_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_BroadcastPLMNinTAISupport_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_BroadcastPLMNinTAISupport_Item_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _BroadcastPLMNinTAISupport_Item_H_ */
#include <asn_internal.h>
