/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_DRBsToBeModified_List_ModRqd_SNterminated_Item_H_
#define	_DRBsToBeModified_List_ModRqd_SNterminated_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_XNAP_DRB-ID.h"
#include "ASN_XNAP_PDCPDuplicationConfiguration.h"
#include "ASN_XNAP_DuplicationActivation.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UPTransportParameters;
struct QoSFlowLevelQoSParameters;
struct ULConfiguration;
struct QoSFlowsModifiedMappedtoDRB_ModRqd_SNterminated;
struct ProtocolExtensionContainer;

/* DRBsToBeModified-List-ModRqd-SNterminated-Item */
typedef struct DRBsToBeModified_List_ModRqd_SNterminated_Item {
	DRB_ID_t	 drb_ID;
	struct UPTransportParameters	*sN_UL_PDCP_UP_TNLInfo	/* OPTIONAL */;
	struct QoSFlowLevelQoSParameters	*dRB_QoS	/* OPTIONAL */;
	struct UPTransportParameters	*secondary_SN_UL_PDCP_UP_TNLInfo	/* OPTIONAL */;
	struct ULConfiguration	*uL_Configuration	/* OPTIONAL */;
	PDCPDuplicationConfiguration_t	*pdcpDuplicationConfiguration	/* OPTIONAL */;
	DuplicationActivation_t	*duplicationActivation	/* OPTIONAL */;
	struct QoSFlowsModifiedMappedtoDRB_ModRqd_SNterminated	*qoSFlowsMappedtoDRB_ModRqd_SNterminated	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DRBsToBeModified_List_ModRqd_SNterminated_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DRBsToBeModified_List_ModRqd_SNterminated_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_DRBsToBeModified_List_ModRqd_SNterminated_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_DRBsToBeModified_List_ModRqd_SNterminated_Item_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _DRBsToBeModified_List_ModRqd_SNterminated_Item_H_ */
#include <asn_internal.h>
