/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_DRBsToBeModifiedList_ModificationResponse_SNterminated_Item_H_
#define	_DRBsToBeModifiedList_ModificationResponse_SNterminated_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_XNAP_DRB-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASN_XNAP_UPTransportParameters;
struct ASN_XNAP_QoSFlowLevelQoSParameters;
struct ASN_XNAP_QoSFlowsMappedtoDRB_SetupResponse_SNterminated;
struct ASN_XNAP_ProtocolExtensionContainer;

/* DRBsToBeModifiedList-ModificationResponse-SNterminated-Item */
typedef struct ASN_XNAP_DRBsToBeModifiedList_ModificationResponse_SNterminated_Item {
    ASN_XNAP_DRB_ID_t	 drb_ID;
	struct ASN_XNAP_UPTransportParameters	*sN_UL_PDCP_UP_TNLInfo	/* OPTIONAL */;
	struct ASN_XNAP_QoSFlowLevelQoSParameters	*dRB_QoS	/* OPTIONAL */;
	struct ASN_XNAP_QoSFlowsMappedtoDRB_SetupResponse_SNterminated	*qoSFlowsMappedtoDRB_SetupResponse_SNterminated	/* OPTIONAL */;
	struct ASN_XNAP_ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_DRBsToBeModifiedList_ModificationResponse_SNterminated_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DRBsToBeModifiedList_ModificationResponse_SNterminated_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_DRBsToBeModifiedList_ModificationResponse_SNterminated_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_DRBsToBeModifiedList_ModificationResponse_SNterminated_Item_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _DRBsToBeModifiedList_ModificationResponse_SNterminated_Item_H_ */
#include <asn_internal.h>
