/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-PDU-Contents"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_QoSFlowsActivityNotifyItem_H_
#define	_QoSFlowsActivityNotifyItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ASN_XNAP_QoSFlowIdentifier.h"
#include "ASN_XNAP_UserPlaneTrafficActivityReport.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASN_XNAP_ProtocolExtensionContainer;

/* QoSFlowsActivityNotifyItem */
typedef struct ASN_XNAP_QoSFlowsActivityNotifyItem {
    ASN_XNAP_QoSFlowIdentifier_t	 qosFlowIdentifier;
    ASN_XNAP_UserPlaneTrafficActivityReport_t	 pduSessionLevelUPactivityreport;
	struct ASN_XNAP_ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASN_XNAP_QoSFlowsActivityNotifyItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QoSFlowsActivityNotifyItem;
extern asn_SEQUENCE_specifics_t asn_SPC_QoSFlowsActivityNotifyItem_specs_1;
extern asn_TYPE_member_t asn_MBR_QoSFlowsActivityNotifyItem_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _QoSFlowsActivityNotifyItem_H_ */
#include <asn_internal.h>
