/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_E_UTRAARFCN_H_
#define	_E_UTRAARFCN_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* E-UTRAARFCN */
typedef long	 E_UTRAARFCN_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_E_UTRAARFCN_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E_UTRAARFCN;
asn_struct_free_f E_UTRAARFCN_free;
asn_struct_print_f E_UTRAARFCN_print;
asn_constr_check_f E_UTRAARFCN_constraint;
ber_type_decoder_f E_UTRAARFCN_decode_ber;
der_type_encoder_f E_UTRAARFCN_encode_der;
xer_type_decoder_f E_UTRAARFCN_decode_xer;
xer_type_encoder_f E_UTRAARFCN_encode_xer;
per_type_decoder_f E_UTRAARFCN_decode_uper;
per_type_encoder_f E_UTRAARFCN_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _E_UTRAARFCN_H_ */
#include <asn_internal.h>
