/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#include "ASN_XNAP_PDUSessionResourceChangeConfirmInfo-SNterminated.h"

#include "ASN_XNAP_DataForwardingInfoFromTargetNGRANnode.h"
#include "ASN_XNAP_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_PDUSessionResourceChangeConfirmInfo_SNterminated_1[] = {
	{ ATF_POINTER, 2, offsetof(struct PDUSessionResourceChangeConfirmInfo_SNterminated, dataforwardinginfoTarget),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataForwardingInfoFromTargetNGRANnode,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dataforwardinginfoTarget"
		},
	{ ATF_POINTER, 1, offsetof(struct PDUSessionResourceChangeConfirmInfo_SNterminated, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_6001P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_PDUSessionResourceChangeConfirmInfo_SNterminated_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_PDUSessionResourceChangeConfirmInfo_SNterminated_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PDUSessionResourceChangeConfirmInfo_SNterminated_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dataforwardinginfoTarget */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_PDUSessionResourceChangeConfirmInfo_SNterminated_specs_1 = {
	sizeof(struct PDUSessionResourceChangeConfirmInfo_SNterminated),
	offsetof(struct PDUSessionResourceChangeConfirmInfo_SNterminated, _asn_ctx),
	asn_MAP_PDUSessionResourceChangeConfirmInfo_SNterminated_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_PDUSessionResourceChangeConfirmInfo_SNterminated_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PDUSessionResourceChangeConfirmInfo_SNterminated = {
	"PDUSessionResourceChangeConfirmInfo-SNterminated",
	"PDUSessionResourceChangeConfirmInfo-SNterminated",
	&asn_OP_SEQUENCE,
	asn_DEF_PDUSessionResourceChangeConfirmInfo_SNterminated_tags_1,
	sizeof(asn_DEF_PDUSessionResourceChangeConfirmInfo_SNterminated_tags_1)
		/sizeof(asn_DEF_PDUSessionResourceChangeConfirmInfo_SNterminated_tags_1[0]), /* 1 */
	asn_DEF_PDUSessionResourceChangeConfirmInfo_SNterminated_tags_1,	/* Same as above */
	sizeof(asn_DEF_PDUSessionResourceChangeConfirmInfo_SNterminated_tags_1)
		/sizeof(asn_DEF_PDUSessionResourceChangeConfirmInfo_SNterminated_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PDUSessionResourceChangeConfirmInfo_SNterminated_1,
	2,	/* Elements count */
	&asn_SPC_PDUSessionResourceChangeConfirmInfo_SNterminated_specs_1	/* Additional specs */
};

