/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-PDU-Descriptions"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#include "ASN_XNAP_InitiatingMessage.h"

static const long asn_VAL_1_id_handoverPreparation = 0;
static const long asn_VAL_1_reject = 0;
static const long asn_VAL_2_id_retrieveUEContext = 3;
static const long asn_VAL_2_reject = 0;
static const long asn_VAL_3_id_sNGRANnodeAdditionPreparation = 7;
static const long asn_VAL_3_reject = 0;
static const long asn_VAL_4_id_mNGRANnodeinitiatedSNGRANnodeModificationPreparation = 9;
static const long asn_VAL_4_reject = 0;
static const long asn_VAL_5_id_sNGRANnodeinitiatedSNGRANnodeModificationPreparation = 10;
static const long asn_VAL_5_reject = 0;
static const long asn_VAL_6_id_mNGRANnodeinitiatedSNGRANnodeRelease = 11;
static const long asn_VAL_6_reject = 0;
static const long asn_VAL_7_id_sNGRANnodeinitiatedSNGRANnodeRelease = 12;
static const long asn_VAL_7_reject = 0;
static const long asn_VAL_8_id_sNGRANnodeChange = 14;
static const long asn_VAL_8_reject = 0;
static const long asn_VAL_9_id_xnRemoval = 16;
static const long asn_VAL_9_reject = 0;
static const long asn_VAL_10_id_xnSetup = 17;
static const long asn_VAL_10_reject = 0;
static const long asn_VAL_11_id_nGRANnodeConfigurationUpdate = 18;
static const long asn_VAL_11_reject = 0;
static const long asn_VAL_12_id_e_UTRA_NR_CellResourceCoordination = 25;
static const long asn_VAL_12_reject = 0;
static const long asn_VAL_13_id_cellActivation = 19;
static const long asn_VAL_13_reject = 0;
static const long asn_VAL_14_id_reset = 20;
static const long asn_VAL_14_reject = 0;
static const long asn_VAL_15_id_sNStatusTransfer = 1;
static const long asn_VAL_15_ignore = 1;
static const long asn_VAL_16_id_handoverCancel = 2;
static const long asn_VAL_16_ignore = 1;
static const long asn_VAL_17_id_rANPaging = 4;
static const long asn_VAL_17_reject = 0;
static const long asn_VAL_18_id_xnUAddressIndication = 5;
static const long asn_VAL_18_reject = 0;
static const long asn_VAL_19_id_uEContextRelease = 6;
static const long asn_VAL_19_reject = 0;
static const long asn_VAL_20_id_sNGRANnodeReconfigurationCompletion = 8;
static const long asn_VAL_20_reject = 0;
static const long asn_VAL_21_id_sNGRANnodeCounterCheck = 13;
static const long asn_VAL_21_reject = 0;
static const long asn_VAL_22_id_rRCTransfer = 15;
static const long asn_VAL_22_reject = 0;
static const long asn_VAL_23_id_errorIndication = 21;
static const long asn_VAL_23_ignore = 1;
static const long asn_VAL_24_id_privateMessage = 22;
static const long asn_VAL_24_ignore = 1;
static const long asn_VAL_25_id_notificationControl = 23;
static const long asn_VAL_25_ignore = 1;
static const long asn_VAL_26_id_activityNotification = 24;
static const long asn_VAL_26_ignore = 1;
static const long asn_VAL_27_id_secondaryRATDataUsageReport = 26;
static const long asn_VAL_27_reject = 0;
static const asn_ioc_cell_t asn_IOS_XNAP_ELEMENTARY_PROCEDURES_1_rows[] = {
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_HandoverRequest },
//	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_HandoverRequestAcknowledge },
//	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_HandoverPreparationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_1_id_handoverPreparation },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_1_reject },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_RetrieveUEContextRequest },
//	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_RetrieveUEContextResponse },
//	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_RetrieveUEContextFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_2_id_retrieveUEContext },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_2_reject },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_SNodeAdditionRequest },
//	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_SNodeAdditionRequestAcknowledge },
//	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_SNodeAdditionRequestReject },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_3_id_sNGRANnodeAdditionPreparation },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_3_reject },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_SNodeModificationRequest },
//	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_SNodeModificationRequestAcknowledge },
//	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_SNodeModificationRequestReject },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_4_id_mNGRANnodeinitiatedSNGRANnodeModificationPreparation },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_4_reject },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_SNodeModificationRequired },
//	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_SNodeModificationConfirm },
//	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_SNodeModificationRefuse },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_5_id_sNGRANnodeinitiatedSNGRANnodeModificationPreparation },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_5_reject },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_SNodeReleaseRequest },
//	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_SNodeReleaseRequestAcknowledge },
//	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_SNodeReleaseReject },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_6_id_mNGRANnodeinitiatedSNGRANnodeRelease },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_6_reject },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_SNodeReleaseRequired },
//	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_SNodeReleaseConfirm },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_7_id_sNGRANnodeinitiatedSNGRANnodeRelease },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_7_reject },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_SNodeChangeRequired },
//	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_SNodeChangeConfirm },
//	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_SNodeChangeRefuse },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_8_id_sNGRANnodeChange },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_8_reject },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_XnRemovalRequest },
//	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_XnRemovalResponse },
//	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_XnRemovalFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_9_id_xnRemoval },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_9_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_XnSetupRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_XnSetupResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_XnSetupFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_10_id_xnSetup },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_10_reject },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_NGRANNodeConfigurationUpdate },
//	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_NGRANNodeConfigurationUpdateAcknowledge },
//	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_NGRANNodeConfigurationUpdateFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_11_id_nGRANnodeConfigurationUpdate },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_11_reject },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_E_UTRA_NR_CellResourceCoordinationRequest },
//	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_E_UTRA_NR_CellResourceCoordinationResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_12_id_e_UTRA_NR_CellResourceCoordination },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_12_reject },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_CellActivationRequest },
//	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_CellActivationResponse },
//	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_CellActivationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_13_id_cellActivation },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_13_reject },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_ResetRequest },
//	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_ResetResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_14_id_reset },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_14_reject },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_SNStatusTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_15_id_sNStatusTransfer },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_15_ignore },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_HandoverCancel },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_16_id_handoverCancel },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_16_ignore },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_RANPaging },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_17_id_rANPaging },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_17_reject },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_XnUAddressIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_18_id_xnUAddressIndication },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_18_reject },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_UEContextRelease },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_19_id_uEContextRelease },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_19_reject },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_SNodeReconfigurationComplete },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_20_id_sNGRANnodeReconfigurationCompletion },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_20_reject },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_SNodeCounterCheckRequest },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_21_id_sNGRANnodeCounterCheck },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_21_reject },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_RRCTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_22_id_rRCTransfer },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_22_reject },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_ErrorIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_23_id_errorIndication },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_23_ignore },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_PrivateMessage },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_24_id_privateMessage },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_24_ignore },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_NotificationControlIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_25_id_notificationControl },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_25_ignore },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_ActivityNotification },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_26_id_activityNotification },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_26_ignore },
//	{ "&InitiatingMessage", aioc__type, &asn_DEF_SecondaryRATDataUsageReport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_ProcedureCode, &asn_VAL_27_id_secondaryRATDataUsageReport },
	{ "&criticality", aioc__value, &asn_DEF_Criticality, &asn_VAL_27_reject }
};
static const asn_ioc_set_t asn_IOS_XNAP_ELEMENTARY_PROCEDURES_1[] = {
	27, 5, asn_IOS_XNAP_ELEMENTARY_PROCEDURES_1_rows
};
static int
memb_procedureCode_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_InitiatingMessage_criticality_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_XNAP_ELEMENTARY_PROCEDURES_1;
	size_t constraining_column = 3; /* &procedureCode */
	size_t for_column = 4; /* &criticality */
	size_t row;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct InitiatingMessage, procedureCode));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = row + 1;
	        break;
	    }
	}
	
	return result;
}

static int
memb_criticality_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_type_selector_result_t
select_InitiatingMessage_value_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_XNAP_ELEMENTARY_PROCEDURES_1;
	size_t constraining_column = 3; /* &procedureCode */
	size_t for_column = 0; /* &InitiatingMessage */
	size_t row;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct InitiatingMessage, procedureCode));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = row + 1;
	        break;
	    }
	}
	
	return result;
}

static int
memb_value_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_per_constraints_t asn_PER_memb_procedureCode_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_criticality_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_value_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_value_4[] = {
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.HandoverRequest),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_HandoverRequest,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"HandoverRequest"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.RetrieveUEContextRequest),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_RetrieveUEContextRequest,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"RetrieveUEContextRequest"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.SNodeAdditionRequest),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_SNodeAdditionRequest,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"SNodeAdditionRequest"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.SNodeModificationRequest),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_SNodeModificationRequest,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"SNodeModificationRequest"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.SNodeModificationRequired),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_SNodeModificationRequired,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"SNodeModificationRequired"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.SNodeReleaseRequest),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_SNodeReleaseRequest,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"SNodeReleaseRequest"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.SNodeReleaseRequired),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_SNodeReleaseRequired,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"SNodeReleaseRequired"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.SNodeChangeRequired),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_SNodeChangeRequired,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"SNodeChangeRequired"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.XnRemovalRequest),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_XnRemovalRequest,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"XnRemovalRequest"
//		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.XnSetupRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_XnSetupRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"XnSetupRequest"
		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.NGRANNodeConfigurationUpdate),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_NGRANNodeConfigurationUpdate,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"NGRANNodeConfigurationUpdate"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.E_UTRA_NR_CellResourceCoordinationRequest),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_E_UTRA_NR_CellResourceCoordinationRequest,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"E-UTRA-NR-CellResourceCoordinationRequest"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.CellActivationRequest),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_CellActivationRequest,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"CellActivationRequest"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.ResetRequest),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_ResetRequest,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"ResetRequest"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.SNStatusTransfer),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_SNStatusTransfer,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"SNStatusTransfer"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.HandoverCancel),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_HandoverCancel,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"HandoverCancel"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.RANPaging),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_RANPaging,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"RANPaging"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.XnUAddressIndication),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_XnUAddressIndication,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"XnUAddressIndication"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.UEContextRelease),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_UEContextRelease,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"UEContextRelease"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.SNodeReconfigurationComplete),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_SNodeReconfigurationComplete,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"SNodeReconfigurationComplete"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.SNodeCounterCheckRequest),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_SNodeCounterCheckRequest,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"SNodeCounterCheckRequest"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.RRCTransfer),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_RRCTransfer,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"RRCTransfer"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.ErrorIndication),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_ErrorIndication,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"ErrorIndication"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.PrivateMessage),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_PrivateMessage,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"PrivateMessage"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.NotificationControlIndication),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_NotificationControlIndication,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"NotificationControlIndication"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.ActivityNotification),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_ActivityNotification,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"ActivityNotification"
//		},
//	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage__value, choice.SecondaryRATDataUsageReport),
//		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
//		0,
//		&asn_DEF_SecondaryRATDataUsageReport,
//		0,
//		{ 0, 0, 0 },
//		0, 0, /* No default value */
//		"SecondaryRATDataUsageReport"
//		},
};
static const asn_TYPE_tag2member_t asn_MAP_value_tag2el_4[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 26 }, /* HandoverRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 25 }, /* RetrieveUEContextRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -2, 24 }, /* SNodeAdditionRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -3, 23 }, /* SNodeModificationRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -4, 22 }, /* SNodeModificationRequired */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -5, 21 }, /* SNodeReleaseRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 6, -6, 20 }, /* SNodeReleaseRequired */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 7, -7, 19 }, /* SNodeChangeRequired */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 8, -8, 18 }, /* XnRemovalRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 9, -9, 17 }, /* XnSetupRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 10, -10, 16 }, /* NGRANNodeConfigurationUpdate */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 11, -11, 15 }, /* E-UTRA-NR-CellResourceCoordinationRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 12, -12, 14 }, /* CellActivationRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 13, -13, 13 }, /* ResetRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 14, -14, 12 }, /* SNStatusTransfer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 15, -15, 11 }, /* HandoverCancel */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 16, -16, 10 }, /* RANPaging */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 17, -17, 9 }, /* XnUAddressIndication */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 18, -18, 8 }, /* UEContextRelease */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 19, -19, 7 }, /* SNodeReconfigurationComplete */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 20, -20, 6 }, /* SNodeCounterCheckRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 21, -21, 5 }, /* RRCTransfer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 22, -22, 4 }, /* ErrorIndication */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 23, -23, 3 }, /* PrivateMessage */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 24, -24, 2 }, /* NotificationControlIndication */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 25, -25, 1 }, /* ActivityNotification */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 26, -26, 0 } /* SecondaryRATDataUsageReport */
};
static asn_CHOICE_specifics_t asn_SPC_value_specs_4 = {
	sizeof(struct InitiatingMessage__value),
	offsetof(struct InitiatingMessage__value, _asn_ctx),
	offsetof(struct InitiatingMessage__value, present),
	sizeof(((struct InitiatingMessage__value *)0)->present),
	asn_MAP_value_tag2el_4,
	27,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_value_4 = {
	"value",
	"value",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	asn_MBR_value_4,
	27,	/* Elements count */
	&asn_SPC_value_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_InitiatingMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage, procedureCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProcedureCode,
		0,
		{ 0, &asn_PER_memb_procedureCode_constr_2,  memb_procedureCode_constraint_1 },
		0, 0, /* No default value */
		"procedureCode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage, criticality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Criticality,
		select_InitiatingMessage_criticality_type,
		{ 0, &asn_PER_memb_criticality_constr_3,  memb_criticality_constraint_1 },
		0, 0, /* No default value */
		"criticality"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct InitiatingMessage, value),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_value_4,
		select_InitiatingMessage_value_type,
		{ 0, &asn_PER_memb_value_constr_4,  memb_value_constraint_1 },
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_InitiatingMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_InitiatingMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* procedureCode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* criticality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_InitiatingMessage_specs_1 = {
	sizeof(struct InitiatingMessage),
	offsetof(struct InitiatingMessage, _asn_ctx),
	asn_MAP_InitiatingMessage_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_InitiatingMessage = {
	"InitiatingMessage",
	"InitiatingMessage",
	&asn_OP_SEQUENCE,
	asn_DEF_InitiatingMessage_tags_1,
	sizeof(asn_DEF_InitiatingMessage_tags_1)
		/sizeof(asn_DEF_InitiatingMessage_tags_1[0]), /* 1 */
	asn_DEF_InitiatingMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_InitiatingMessage_tags_1)
		/sizeof(asn_DEF_InitiatingMessage_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_InitiatingMessage_1,
	3,	/* Elements count */
	&asn_SPC_InitiatingMessage_specs_1	/* Additional specs */
};

