/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-PDU-Contents"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_PDUSessionToBeReleasedList_RelRqd_H_
#define	_PDUSessionToBeReleasedList_RelRqd_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PDUSession_List_withDataForwardingRequest;
struct ProtocolExtensionContainer;

/* PDUSessionToBeReleasedList-RelRqd */
typedef struct PDUSessionToBeReleasedList_RelRqd {
	struct PDUSession_List_withDataForwardingRequest	*pduSessionsToBeReleasedList_SNterminated	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDUSessionToBeReleasedList_RelRqd_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDUSessionToBeReleasedList_RelRqd;

#ifdef __cplusplus
}
#endif

#endif	/* _PDUSessionToBeReleasedList_RelRqd_H_ */
#include <asn_internal.h>
