/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_E_UTRA_CoordinationAssistanceInfo_H_
#define	_E_UTRA_CoordinationAssistanceInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E_UTRA_CoordinationAssistanceInfo {
	E_UTRA_CoordinationAssistanceInfo_coordination_not_required	= 0
	/*
	 * Enumeration is extensible
	 */
} e_E_UTRA_CoordinationAssistanceInfo;

/* E-UTRA-CoordinationAssistanceInfo */
typedef long	 E_UTRA_CoordinationAssistanceInfo_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_E_UTRA_CoordinationAssistanceInfo_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E_UTRA_CoordinationAssistanceInfo;
extern const asn_INTEGER_specifics_t asn_SPC_E_UTRA_CoordinationAssistanceInfo_specs_1;
asn_struct_free_f E_UTRA_CoordinationAssistanceInfo_free;
asn_struct_print_f E_UTRA_CoordinationAssistanceInfo_print;
asn_constr_check_f E_UTRA_CoordinationAssistanceInfo_constraint;
ber_type_decoder_f E_UTRA_CoordinationAssistanceInfo_decode_ber;
der_type_encoder_f E_UTRA_CoordinationAssistanceInfo_encode_der;
xer_type_decoder_f E_UTRA_CoordinationAssistanceInfo_decode_xer;
xer_type_encoder_f E_UTRA_CoordinationAssistanceInfo_encode_xer;
per_type_decoder_f E_UTRA_CoordinationAssistanceInfo_decode_uper;
per_type_encoder_f E_UTRA_CoordinationAssistanceInfo_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _E_UTRA_CoordinationAssistanceInfo_H_ */
#include <asn_internal.h>
