/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_NG_RAN_CellPCI_H_
#define	_NG_RAN_CellPCI_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRPCI.h"
#include "E-UTRAPCI.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NG_RAN_CellPCI_PR {
	NG_RAN_CellPCI_PR_NOTHING,	/* No components present */
	NG_RAN_CellPCI_PR_nr,
	NG_RAN_CellPCI_PR_e_utra,
	NG_RAN_CellPCI_PR_choice_extension
} NG_RAN_CellPCI_PR;

/* Forward declarations */
struct ProtocolIE_Single_Container;

/* NG-RAN-CellPCI */
typedef struct NG_RAN_CellPCI {
	NG_RAN_CellPCI_PR present;
	union NG_RAN_CellPCI_u {
		NRPCI_t	 nr;
		E_UTRAPCI_t	 e_utra;
		struct ProtocolIE_Single_Container	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NG_RAN_CellPCI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NG_RAN_CellPCI;
extern asn_CHOICE_specifics_t asn_SPC_NG_RAN_CellPCI_specs_1;
extern asn_TYPE_member_t asn_MBR_NG_RAN_CellPCI_1[3];
extern asn_per_constraints_t asn_PER_type_NG_RAN_CellPCI_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NG_RAN_CellPCI_H_ */
#include <asn_internal.h>
