/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "XnAP-IEs"
 * 	found in "./xnap-15.5.0.asn1"
 * 	`asn1c -fcompound-names -pdu=all -findirect-choice -fno-include-deps -gen-PER -no-gen-OER -no-gen-example -D xnap`
 */

#ifndef	_ServedCellInformation_E_UTRA_FDDInfo_H_
#define	_ServedCellInformation_E_UTRA_FDDInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "E-UTRAARFCN.h"
#include "E-UTRATransmissionBandwidth.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* ServedCellInformation-E-UTRA-FDDInfo */
typedef struct ServedCellInformation_E_UTRA_FDDInfo {
	E_UTRAARFCN_t	 ul_earfcn;
	E_UTRAARFCN_t	 dl_earfcn;
	E_UTRATransmissionBandwidth_t	 ul_e_utraTxBW;
	E_UTRATransmissionBandwidth_t	 dl_e_utraTxBW;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServedCellInformation_E_UTRA_FDDInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServedCellInformation_E_UTRA_FDDInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_ServedCellInformation_E_UTRA_FDDInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_ServedCellInformation_E_UTRA_FDDInfo_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _ServedCellInformation_E_UTRA_FDDInfo_H_ */
#include <asn_internal.h>
